local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")

AtlasLoot:AddNewMenus({
	-- ClassicRaid
    ["ZulGurub"] = {
        Module = "AtlasLoot_OriginalWoW",
        Name = "Zul'Gurub",
        Type = "ClassicRaid",
        Map = "ZulGurub",
		{ "Bloodlord Mandokir", {} },
		{ "Gahz'ranka", {} },
		{ "Hakkar", {} },
		{ "High Priest Thekal", {} },
		{ "High Priest Venoxis", {} },
		{ "High Priestess Arlokk", {} },
		{ "High Priestess Jeklik", {} },
		{ "High Priestess Mar'li", {} },
		{ "Jin'do the Hexxer", {} },
		{ "Edge of Madness", {} },
		{ "Madness", {} },
		{ "Shared ZG Priest Drops", {} },
		{ "Zul'Gurub", {} },
		{ "Trash Mobs", {} },
		{ "Bijous & Coins", {} },
		{ "World Drops", {} },
    },

	["Onyxia60"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Onyxia's Lair",
		Type = "ClassicRaid",
		Map = "Onyxia60",
		{ "Basalthane", {} },
		{ "Onyxia", {} },
	},

	["RuinsofAQ"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Ruins of Ahn'Qiraj",
		Type = "ClassicRaid",
		Map = "TheRuinsofAhnQiraj",
		{ "Kurinnaxx", { 15348 } },
		{ "General Rajaxx", { 15341 } },
		{ "Moam", { 15340 } },
		{ "Buru the Gorger", { 15370 } },
		{ "Ayamiss the Hunter", { 15369 } },
		{ "Ossirian the Unscarred", { 15339 } },
		{ "Trash Mobs", {} },
		{ "AQ Enchants", {} },
		{ "Page 9", {} },
		{ "Ayamiss the Hunter", {} },
		{ "Buru the Gorger", {} },
		{ "General Rajaxx", {} },
		{ "Kurinnaxx", {} },
		{ "Moam", {} },
		{ "Ossirian the Unscarred", {} },
		{ "Trash Mobs", {} },
	},

	["TempleofAQ"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Temple of Ahn'Qiraj",
		Type = "ClassicRaid",
		Map = "TheTempleofAhnQiraj",
		{ "The Prophet Skeram", { 15263 } },
		{ "The Bug Family", {} },
		{ "Battleguard Sartura", { 15516 } },
		{ "Fankriss the Unyielding", { 15510 } },
		{ "Viscidus", { 15299 } },
		{ "Princess Huhuran", { 15509 } },
		{ "The Twin Emperors", { 15275 } },
		{ "Ouro", { 15517 }, {} },
		{ "C'Thun", { 15727 }, {} },
		{ "Trash Mobs", {} },
		{ "Shoulder Enchants", {} },
		{ "Trash Mobs", {} },
		{ "Battleguard Sartura", {} },
		{ "C'Thun", {} },
		{ "Fankriss the Unyielding", {} },
		{ "Ouro", {} },
		{ "Princess Huhuran", {} },
		{ "The Bug Family", {} },
		{ "The Prophet Skeram", {} },
		{ "The Twin Emperors", {} },
		{ "Viscidus", {} },
		{ "Trash Mobs", {} },
	},

	["AQOpening"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "AQOpening",
		{ "AQOpening", {} },
	},

	["Naxxramas60"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Naxxramas",
		Type = "ClassicRaid",
		Map = "Naxxramas60",
		{ "Patchwerk", { 16028 } },
		{ "Grobbulus", { 15931 } },
		{ "Gluth", { 15932 } },
		{ "Thaddius", { 15928 } },
		{ "Anub'Rekhan", { 15956 } },
		{ "Grand Widow Faerlina", { 15953 } },
		{ "Maexxna", { 15952 } },
		{ "Instructor Razuvious", { 16061 } },
		{ "Gothik the Harvester", { 16060 } },
		{ "The Four Horsemen", {} },
		{ "Noth the Plaguebringer", { 15954 } },
		{ "Heigan the Unclean", { 15936 } },
		{ "Loatheb", { 16011 } },
		{ "Sapphiron", { 15989 } },
		{ "Kel'Thuzad", { 15990 } },
		{ "Shared Frost Resistance Gear", {} },
		{ "Trash Mobs", {} },
		{ "Anub'Rekhan", {} },
		{ "Gluth", {} },
		{ "Gothik the Harvester", {} },
		{ "Grand Widow Faerlina", {} },
		{ "Grobbulus", {} },
		{ "Heigan the Unclean", {} },
		{ "Instructor Razuvious", {} },
		{ "Kel'Thuzad", {} },
		{ "Loatheb", {} },
		{ "Maexxna", {} },
		{ "Naxxramas", {} },
		{ "Noth the Plaguebringer", {} },
		{ "Patchwerk", {} },
		{ "Sapphiron", {} },
		{ "Thaddius", {} },
		{ "The Four Horsemen", {} },
		{ "Trash Mobs", {} },
	},

	["WorldBossesCLASSIC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "World Bosses",
		Type = "ClassicRaid",
		{ "Azuregos", {6109} },
		{ "Lord Kazzak", {12397} },
		{ "Ysondre", {} },
		{ "Lethon", {} },
		{ "Emeriss", {} },
		{ "Taerar", {} },
		{ "Setis", {} },
		{ "Snowgrave", {} },
		{ "The Will of Soggoth", {} },
		{ "Atal'zul, the Soulreaver", {} },
		{ "Quest Items", {} },
	},

	-- ClassicDungeons
	["BlackfathomDeeps"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackfathom Deeps",
		Type = "ClassicDungeonExt",
		Map = "BlackfathomDeeps",
		{ "Ghamoo-ra", { 4887 } },
		{ "Lady Sarevess", { 4831 } },
		{ "Gelihast", { 6243 } },
		{ "Baron Aquanis", { 12876 } },
		{ "Twilight Lord Kelris", { 4832 } },
		{ "Old Serra'kis", { 4830 } },
		{ "Aku'mai", { 4829 } },
		{ "Trash Mobs", {} },
		{ "Aku'mai", {} },
		{ "Gelihast", {} },
		{ "Ghamoo-ra", {} },
		{ "Lady Sarevess", {} },
		{ "Old Serra'kis", {} },
		{ "Twilight Lord Kelris", {} },
		{ "Trash Mobs", {} },
	},

	["BlackrockDepths"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackrock Depths",
		Type = "ClassicDungeonExt",
		Map = "BlackrockDepths",
		{ "Overmaster Pyron", {} },
		{ "Lord Roccor", { 9025 } },
		{ "High Interrogator Gerstahn", { 9018 } },
		{ "Ring of Law", {} },
		{ "Theldren", {} },
		{ "Houndmaster Grebmar", { 9319 } },
		{ "Monument of Franclorn Forgewright", {} },
		{ "Pyromancer Loregrain", { 9024 } },
		{ "The Vault", {} },
		{ "Warder Stilgiss", { 9041 } },
		{ "Verek", { 9042 }, {} },
		{ "Fineous Darkvire", { 9056 } },
		{ "Lord Incendius", { 9017 } },
		{ "Bael'Gar", { 9016 } },
		{ "General Angerforge", { 9033 } },
		{ "Golem Lord Argelmach", { 8983 } },
		{ "Hurley Blackbreath", { 9537 } },
		{ "Phalanx", { 9502 } },
		{ "Ribbly Screwspigot", {} },
		{ "Plugger Spazzring", {} },
		{ "Ambassador Flamelash", { 9156 } },
		{ "Panzor the Invincible (Rare)", {} },
		{ "Summoner's Tomb", {} },
		{ "Shadowforge Flame Keeper", {} },
		{ "Magmus", { 9938 } },
		{ "Emperor Dagran Thaurissan", { 9019 } },
		{ "Princess Moira Bronzebeard", {} },
		{ "Blacksmith Plans", {} },
		{ "Trash Mobs", {} },
		{ "Ambassador Flamelash", {} },
		{ "Bael'Gar", {} },
		{ "Emperor Dagran Thaurissan", {} },
		{ "Fineous Darkvire", {} },
		{ "General Angerforge", {} },
		{ "Golem Lord Argelmach", {} },
		{ "High Interrogator Gerstahn", {} },
		{ "Houndmaster Grebmar", {} },
		{ "Hurley Blackbreath", {} },
		{ "Lord Incendius", {} },
		{ "Lord Roccor", {} },
		{ "Magmus", {} },
		{ "Panzor the Invincible (Rare)", {} },
		{ "Phalanx", {} },
		{ "Plugger Spazzring", {} },
		{ "Princess Moira Bronzebeard", {} },
		{ "Pyromancer Loregrain", {} },
		{ "Ribbly Screwspigot", {} },
		{ "Ring of Law", {} },
		{ "Summoner's Tomb", {} },
		{ "The Vault", {} },
		{ "Theldren", {} },
		{ "Verek", {} },
		{ "Warder Stilgiss", {} },
		{ "Trash Mobs", {} },
	},

	["BlackrockCavernsCLASSIC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackrock Caverns",
		Type = "ClassicDungeonExt",
		{ "Rom'ogg Bonecrusher", {}, WebID = { 39665, "npc"} },
		{ "Corla, Herald of Twilight", {}, WebID = {39679, "npc"} },
		{ "Karsh Steelbender <Twilight Armorer>", {}, WebID = {39698, "npc"} },
		{ "Beauty", {}, WebID = { 39700, "npc"} },
		{ "Ascendant Lord Obsidius", {}, WebID = {39705, "npc"} },
		{ "Ascendant Lord Obsidius", {} },
		{ "Beauty", {} },
		{ "Corla, Herald of Twilight", {} },
		{ "Karsh Steelbender <Twilight Armorer>", {} },
		{ "Rom'ogg Bonecrusher", {} },
	},

	["LowerBlackrock"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Lower Blackrock Spire",
		Type = "ClassicDungeonExt",
		Loadfirst = 3,
		Map = "BlackrockSpire",
		{ "Scarshield Quartermaster", {} },
		{ "Quest Item", {} },
		{ "Spirestone Butcher (Rare)", {9219,2075549} },
		{ "Highlord Omokk", {9196,2075540} },
		{ "Spirestone Battle Lord (Rare)", {} },
		{ "Spirestone Lord Magus (Rare)", {} },
		{ "Shadow Hunter Vosh'gajin", {9236,2061376} },
		{ "War Master Voone", {9237,2062131} },
		{ "Mor Grayhoof (Summon)", {16080,2060519} },
		{ "Bannok Grimaxe (Rare)", {9596,2061362} },
		{ "Mother Smolderweb", {10596} },
		{ "Crystal Fang", {10376} },
		{ "Urok Doomhowl (Summon)", {10584,2075664} },
		{ "Quartermaster Zigris", {9736,2060343} },
		{ "Gizrul the Slavener", {10268} },
		{ "Halycon", {10220} },
		{ "Ghok Bashguud (Rare)", {9718,2060448} },
		{ "Overlord Wyrmthalak", {9568, 2075591} },
		{ "Burning Felguard (Rare, Random)", {} },
		{ "Trash Mobs", {} },
		{ "Highlord Omokk", {} },
		{ "Mor Grayhoof (Summon)", {} },
		{ "Mother Smolderweb", {} },
		{ "Overlord Wyrmthalak", {} },
		{ "Quartermaster Zigris", {} },
		{ "Shadow Hunter Vosh'gajin", {} },
		{ "Spirestone Battle Lord (Rare)", {} },
		{ "Spirestone Butcher (Rare)", {} },
		{ "Spirestone Lord Magus (Rare)", {} },
		{ "Urok Doomhowl (Summon)", {} },
		{ "War Master Voone", {} },
	},

	["UpperBlackrock"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Upper Blackrock Spire",
		Type = "ClassicDungeonExt",
		Map = "BlackrockSpire",
		{ "Pyroguard Emberseer", {} },
		{ "Solakar Flamewreath", {} },
		{ "Father Flame", {} },
		{ "Quest Item", {} },
		{ "Jed Runewatcher", {} },
		{ "Goraluk Anvilcrack", { 10899 } },
		{ "Warchief Rend Blackhand", { 10429 } },
		{ "Gyth", {} },
		{ "The Beast", { 10430 } },
		{ "Lord Valthalak (Summon)", {} },
		{ "General Drakkisath", { 10363 } },
		{ "Trash Mobs", {} },
		{ "Father Flame", {} },
		{ "General Drakkisath", {} },
		{ "Goraluk Anvilcrack", {} },
		{ "Gyth", {} },
		{ "Jed Runewatcher", {} },
		{ "Lord Valthalak (Summon)", {} },
		{ "Pyroguard Emberseer", {} },
		{ "Solakar Flamewreath", {} },
		{ "The Beast", {} },
		{ "Warchief Rend Blackhand", {} },
	},

	["MoltenCore"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Molten Core",
		Type = "ClassicRaid",
		Map = "MoltenCore",
		{ "Lucifron", { 12118 } },
		{ "Magmadar", { 11982 } },
		{ "Gehennas", { 12259 } },
		{ "Garr", { 12057 } },
		{ "Baron Geddon", { 12056 } },
		{ "Shazzrah", { 12264 } },
		{ "Golemagg the Incinerator", { 11988 } },
		{ "Sulfuron Harbinger", { 12098 } },
		{ "Majordomo Executus", { 12018 } },
		{ "Ragnaros", { 11502 } },
		{ "Molten Core", {} },
		{ "Random Boss Drops", {} },
		{ "Trash Mobs", {} },
	},

	["BlackwingLair"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackwing Lair",
		Type = "ClassicRaid",
		Map = "BlackwingLair",
		{ "Razorgore the Untamed", { 12435 } },
		{ "Vaelastrasz the Corrupt", { 13020 } },
		{ "Broodlord Lashlayer", { 12017 } },
		{ "Firemaw", { 11983 } },
		{ "Ebonroc", { 14601 } },
		{ "Flamegor", { 11981 } },
		{ "Chromaggus", { 14020 } },
		{ "Nefarian", { 11583 } },
		{ "Trash Mobs", {} },
		{ "Blackwing Lair", {} },
		{ "Broodlord Lashlayer", {} },
		{ "Chromaggus", {} },
		{ "Ebonroc", {} },
		{ "Firemaw", {} },
		{ "Flamegor", {} },
		{ "Nefarian", {} },
		{ "Razorgore the Untamed", {} },
		{ "Vaelastrasz the Corrupt", {} },
		{ "Trash Mobs", {} },
	},

	["DireMaulEast"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul East",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		MapNum = 5,
		{ "Pusillin", {} },
		{ "Zevrim Thornhoof", { 11490 } },
		{ "Lethtendris", { 14327 } },
		{ "Pimgib", {} },
		{ "Hydrospawn", { 13280 } },
		{ "Alzzin the Wildshaper", { 11492 } },
		{ "Isalien", {} },
		{ "Trash Mobs", {} },
		{ "Dire Maul Books", {} },
		{ "Alzzin the Wildshaper", {} },
		{ "Hydrospawn", {} },
		{ "Isalien", {} },
		{ "Lethtendris", {} },
		{ "Pimgib", {} },
		{ "Zevrim Thornhoof", {} },
		{ "Trash Mobs", {} },
	},

	["DireMaulNorth"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul North",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		MapNum = 1,
		{ "Guard Mol'dar", { 14326 } },
		{ "Stomper Kreeg", { 14322 } },
		{ "Guard Fengus", { 14321 } },
		{ "Knot Thimblejack", {} },
		{ "Guard Slip'kik", { 14323 } },
		{ "Captain Kromcrush", { 14325 } },
		{ "Cho'Rush the Observer", { 14324 } },
		{ "King Gordok", { 11501 } },
		{ "DM North Tribute Chest", {} },
		{ "Captain Kromcrush", {} },
		{ "Cho'Rush the Observer", {} },
		{ "DM North Tribute Chest", {} },
		{ "Guard Fengus", {} },
		{ "Guard Mol'dar", {} },
		{ "Guard Slip'kik", {} },
		{ "King Gordok", {} },
		{ "Stomper Kreeg", {} },
	},

	["DireMaulWest"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul West",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		MapNum = 2,
		{ "Tendris Warpwood", { 11489 } },
		{ "Illyanna Ravenoak", { 11488 } },
		{ "Magister Kalendris", { 11487 } },
		{ "Tsu'zee", { 11467 } },
		{ "Immol'thar", { 11496 } },
		{ "Lord Hel'nurath", { 14506 } },
		{ "Prince Tortheldrin", { 11486 } },
		{ "Shen'dralar Provisioner", {} },
		{ "Trash Mobs", {} },
		{ "Illyanna Ravenoak", {} },
		{ "Immol'thar", {} },
		{ "Lord Hel'nurath", {} },
		{ "Magister Kalendris", {} },
		{ "Prince Tortheldrin", {} },
		{ "Tendris Warpwood", {} },
		{ "Tsu'zee", {} },
		{ "Trash Mobs", {} },
	},

	["Gnomeregan"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Gnomeregan",
		Type = "ClassicDungeonExt",
		Map = "Gnomeregan",
		{ "Namdo Bizzfizzle", {} },
		{ "Techbot", { 6231 } },
		{ "Grubbis", { 7361 } },
		{ "Viscous Fallout", { 7079 } },
		{ "Electrocutioner 6000", { 6235 } },
		{ "Crowd Pummeler 9-60", { 6229 } },
		{ "Dark Iron Ambassador", { 6228 } },
		{ "Mekgineer Thermaplugg", { 7800 } },
		{ "Trash Mobs", {} },
		{ "Crowd Pummeler 9-60", {} },
		{ "Dark Iron Ambassador", {} },
		{ "Electrocutioner 6000", {} },
		{ "Grubbis", {} },
		{ "Mekgineer Thermaplugg", {} },
		{ "Techbot", {} },
		{ "Viscous Fallout", {} },
		{ "Trash Mobs", {} },
		{ "Techbot", {} },
	},

	["KarazhanCrypts"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Karazhan Crypts",
		Type = "ClassicDungeonExt",
		{ "Cynfael", {}, WebID = {254401,"npc"} },
		{ "Dryn Miel <The Second Eidolon>", {}, WebID =  {254413,"npc"} },
		{ "Kurgoth Doomreaver", {}, WebID = {254406,"npc"} },
		{ "The Judgement of Sinners",  {}, WebID =  {254405,"npc"} },
		{ "Captain Taveir (Rare Spawn)",  {}, WebID =  {254495,"npc"} },
		{ "Kelivex Autumnvale (Rare Spawn)",  {}, WebID =  {254493,"npc"} },
	},

	["Maraudon"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Maraudon",
		Type = "ClassicDungeonExt",
		Map = "Maraudon",
		{ "Noxxion", {} },
		{ "Razorlash", {} },
		{ "Lord Vyletongue", {2075821} },
		{ "Meshlok the Harvester", {} },
		{ "Celebras the Cursed", {2075820} },
		{ "Landslide", {} },
		{ "Tinkerer Gizlock", {2062870} },
		{ "Rotgrip", {} },
		{ "Princess Theradras", {12201} },
		{ "Quest Item", {} },
		{ "Celebras the Cursed", {} },
		{ "Landslide", {} },
		{ "Lord Vyletongue", {} },
		{ "Meshlok the Harvester", {} },
		{ "Noxxion", {} },
		{ "Princess Theradras", {} },
		{ "Razorlash", {} },
		{ "Rotgrip", {} },
		{ "Tinkerer Gizlock", {} },
	},

	["RagefireChasm"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Ragefire Chasm",
		Type = "ClassicDungeonExt",
		Map = "RagefireChasm",
		{ "Taragaman the Hungerer", {11520,2075751} },
		{ "Zelemar the Wrathful", {17830} },
		{ "Jergosh the Invoker", {11518,2061477} },
		{ "Oggleflint", {11517,2075748} },
		{ "Jergosh the Invoker", {} },
		{ "Oggleflint", {} },
		{ "Taragaman the Hungerer", {} },
		{ "Zelemar the Wrathful", {} },
	},

	["RazorfenDowns"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Razorfen Downs",
		Type = "ClassicDungeonExt",
		Map = "RazorfenDowns",
		{ "Tuten'kash", {} },
		{ "Henry Stern", {5594} },
		{ "Mordresh Fire Eye", {} },
		{ "Glutton", {} },
		{ "Ragglesnout", {2075397} },
		{ "Lady Falther'ess", {2063851} },
		{ "Amnennar the Coldbringer", {} },
		{ "Plaguemaw the Rotting", {} },
		{ "Trash Mobs", {} },
		{ "Amnennar the Coldbringer", {} },
		{ "Glutton", {} },
		{ "Lady Falther'ess", {} },
		{ "Mordresh Fire Eye", {} },
		{ "Plaguemaw the Rotting", {} },
		{ "Ragglesnout", {} },
		{ "Tuten'kash", {} },
		{ "Trash Mobs", {} },
	},

	["RazorfenKraul"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Razorfen Kraul",
		Type = "ClassicDungeonExt",
		Map = "RazorfenKraul",
		{ "Roogug", { 6168,2075273 } },
		{ "Aggem Thorncurse", { 4424,2074993 } },
		{ "Death Speaker Jargba", { 4428,2074995 } },
		{ "Razorfen Spearhide", {} },
		{ "Overlord Ramtusk", { 4420,2074991 } },
		{ "Agathelos the Raging", { 4422 } },
		{ "Blind Hunter", { 4425,25874 } },
		{ "Charlga Razorflank", { 4421,2074992 } },
		{ "Earthcaller Halmgar", { 4842,2075098 } },
		{ "Trash Mobs", {} },
		{ "Agathelos the Raging", {} },
		{ "Aggem Thorncurse", {} },
		{ "Blind Hunter", {} },
		{ "Charlga Razorflank", {} },
		{ "Death Speaker Jargba", {} },
		{ "Earthcaller Halmgar", {} },
		{ "Overlord Ramtusk", {} },
		{ "Razorfen Spearhide", {} },
		{ "Roogug", {} },
		{ "Trash Mobs", {} },
	},

	["ScarletMonasteryArmory"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Armory",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 3,
		{ "Herod", {} },
		{ "Trash Mobs", {} },
	},

	["ScarletMonasteryCathedral"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Cathedral",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 4,
		{ "High Inquisitor Fairbanks", {2060073} },
		{ "Scarlet Commander Mograine", {2060012} },
		{ "High Inquisitor Whitemane", {} },
		{ "Trash Mobs", {} },
		{ "High Inquisitor Whitemane", {} },
		{ "Scarlet Commander Mograine", {} },
	},

	["ScarletMonasteryGraveyard"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Graveyard",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 1,
		{ "Interrogator Vishas", {3983,2060013} },
		{ "Bloodmage Thalnos", {} },
		{ "Ironspine", {2075311} },
		{ "Azshir the Sleepless", {2060088} },
		{ "Fallen Champion", {2060214} },
		{ "Trash Mobs", {} },
		{ "Azshir the Sleepless", {} },
		{ "Bloodmage Thalnos", {} },
		{ "Fallen Champion", {} },
		{ "Ironspine", {} },
	},

	["ScarletMonasteryLibrary"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Library",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 2,
		{ "Houndmaster Loksey", {2062271} },
		{ "Arcanist Doan", {2061226} },
		{ "Trash Mobs", {} },
		{ "Arcanist Doan", {} },
	},

	["Scholomance"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scholomance",
		Type = "ClassicDungeonExt",
		Loadfirst = 3,
		Map = "Scholomance",
		{ "Quest Item", {} },
		{ "Blood Steward of Kirtonos", { 14861 } },
		{ "Kirtonos the Herald", {} },
		{ "Jandice Barov", { 10503,2060425 } },
		{ "Rattlegore", { 11622 } },
		{ "Death Knight Darkreaver", {} },
		{ "Vectus", { 10432 } },
		{ "Marduk Blackpool", {2060354} },
		{ "Ras Frostwhisper", { 10508 } },
		{ "Kormok", {} },
		{ "Instructor Malicia", { 10505,2060724 } },
		{ "Doctor Theolen Krastinov", { 11261,2060424 } },
		{ "Lorekeeper Polkelt", { 10901 } },
		{ "The Ravenian", { 10507 } },
		{ "Lord Alexei Barov", { 10504,2060426 } },
		{ "Lady Illucia Barov", { 10502,2060456 } },
		{ "Darkmaster Gandling", {} },
		{ "Trash Mobs", {} },
		{ "Darkmaster Gandling", {} },
		{ "Death Knight Darkreaver", {} },
		{ "Doctor Theolen Krastinov", {} },
		{ "Instructor Malicia", {} },
		{ "Jandice Barov", {} },
		{ "Kirtonos the Herald", {} },
		{ "Kormok", {} },
		{ "Lady Illucia Barov", {} },
		{ "Lady Illucia Barov", {} },
		{ "Lord Alexei Barov", {} },
		{ "Lorekeeper Polkelt", {} },
		{ "Marduk Blackpool", {} },
		{ "Ras Frostwhisper", {} },
		{ "Rattlegore", {} },
		{ "Vectus", {} },
		{ "Trash Mobs", {} },
	},

	["ShadowfangKeep"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Shadowfang Keep",
		Type = "ClassicDungeonExt",
		Map = "ShadowfangKeep",
		{ "Apothecary Hummel", { 36296,2061045 } },
		{ "Deathsworn Captain", {} },
		{ "Rethilgore", { 3914 } },
		{ "Felsteed", {} },
		{ "Razorclaw the Butcher", { 3886 } },
		{ "Baron Silverlaine", { 3887,2062363 } },
		{ "Commander Springvale", { 4278,2061124 } },
		{ "Odo the Blindwatcher", { 4279 } },
		{ "Fenrus the Devourer", { 4274 } },
		{ "Arugal's Voidwalker", {} },
		{ "Wolf Master Nandos", { 3927 } },
		{ "Archmage Arugal", { 4275,2060050 } },
		{ "Trash Mobs", {} },
		{ "Apothecary Hummel", {} },
		{ "Archmage Arugal", {} },
		{ "Baron Silverlaine", {} },
		{ "Commander Springvale", {} },
		{ "Deathsworn Captain", {} },
		{ "Fenrus the Devourer", {} },
		{ "Odo the Blindwatcher", {} },
		{ "Razorclaw the Butcher", {} },
		{ "Rethilgore", {} },
		{ "Wolf Master Nandos", {} },
		{ "Trash Mobs", {} },
	},

	["Stratholme"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Stratholme",
		Type = "ClassicDungeonExt",
		Map = "Stratholme",
		{ "Skul", { 10393 } },
		{ "Mailbox Keys", {} },
		{ "Fras Siabi", {} },
		{ "Atiesh <Hand of Sargeras>", {} },
		{ "Hearthsinger Forresten", { 10558,2061425 } },
		{ "The Unforgiven", { 10516 } },
		{ "Timmy the Cruel", {} },
		{ "Malor's Strongbox", {} },
		{ "Crimson Hammersmith (Summon)", {} },
		{ "Plans: Serenity", {} },
		{ "Cannon Master Willey", { 10997,2061445 } },
		{ "Archivist Galford", { 10811,2060422 } },
		{ "Balnazzar", {} },
		{ "Sothos and Jarien", {} },
		{ "Stonespine", { 10809 } },
		{ "Baroness Anastari", { 10436 } },
		{ "Black Guard Swordsmith (Summon)", {} },
		{ "Plans: Corruption", {} },
		{ "Nerub'enkan", { 10437 } },
		{ "Maleki the Pallid", { 10438,2060418 } },
		{ "Magistrate Barthilas", { 10435 } },
		{ "Ramstein the Gorger", {} },
		{ "Baron Rivendare", { 10440 } },
		{ "Trash Mobs", {} },
		{ "Archivist Galford", {} },
		{ "Balnazzar", {} },
		{ "Baron Rivendare", {} },
		{ "Baroness Anastari", {} },
		{ "Cannon Master Willey", {} },
		{ "Hearthsinger Forresten", {} },
		{ "Magistrate Barthilas", {} },
		{ "Maleki the Pallid", {} },
		{ "Nerub'enkan", {} },
		{ "Ramstein the Gorger", {} },
		{ "Skul", {} },
		{ "Sothos and Jarien", {} },
		{ "Stonespine", {} },
		{ "The Unforgiven", {} },
		{ "Timmy the Cruel", {} },
		{ "Trash Mobs", {} },
	},

	["TheDeadmines"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Deadmines",
		Type = "ClassicDungeonExt",
		Map = "TheDeadmines",
		{ "Marisa du'Paige", {} },
		{ "Brainwashed Noble", {} },
		{ "Foreman Thistlenettle", {} },
		{ "Rhahk'Zor", { 644 } },
		{ "Miner Johnson", { 3586,2060859 } },
		{ "Sneed's Shredder", { 642 } },
		{ "Sneed", {} },
		{ "Gilnid", { 1763,2062869 } },
		{ "Captain Greenskin", { 647,2060296 } },
		{ "Mr. Smite", { 646,2062269 } },
		{ "Cookie", { 645,2074200 } },
		{ "Edwin VanCleef", { 639,2060010 } },
		{ "Brainwashed Noble", {} },
		{ "Captain Greenskin", {} },
		{ "Cookie", {} },
		{ "Edwin VanCleef", {} },
		{ "Gilnid", {} },
		{ "Marisa du'Paige", {} },
		{ "Miner Johnson", {} },
		{ "Mr. Smite", {} },
		{ "Rhahk'Zor", {} },
		{ "Sneed", {} },
		{ "Sneed's Shredder", {} },
	},

	["TheStockade"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Stockade",
		Type = "ClassicDungeonExt",
		Map = "TheStockade",
		{ "Targorr the Dread", { 1696,2074427 } },
		{ "Kam Deepfury", { 1666,2062387 } },
		{ "Bazil Thredd", { 1716,2060004 } },
		{ "Hamhock", { 1717,2074434 } },
		{ "Dextren Ward", { 1663,2062284 } },
		{ "Bruegal Ironknuckle", { 1720,2062246 } },
		{ "Quest Item's", {} },
		{ "Bazil Thredd", {} },
		{ "Bruegal Ironknuckle", {} },
		{ "Dextren Ward", {} },
		{ "Hamhock", {} },
		{ "Kam Deepfury", {} },
		{ "Targorr the Dread", {} },
	},

	["SunkenTemple"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Sunken Temple",
		Type = "ClassicDungeonExt",
		Map = "TheSunkenTemple",
		{ "Spawn of Hakkar", { 5708 } },
		{ "Troll Minibosses", {} },
		{ "Atal'alarion", {} },
		{ "Dreamscythe", { 5721 } },
		{ "Weaver", {} },
		{ "Avatar of Hakkar", { 8443 } },
		{ "Jammal'an the Prophet", {2061283} },
		{ "Ogom the Wretched", {2060266} },
		{ "Morphaz", {} },
		{ "Hazzas", {} },
		{ "Shade of Eranikus", { 5709 } },
		{ "Trash Mobs", {} },
		{ "Atal'alarion", {} },
		{ "Avatar of Hakkar", {} },
		{ "Hazzas", {} },
		{ "Jammal'an the Prophet", {} },
		{ "Ogom the Wretched", {} },
		{ "Shade of Eranikus", {} },
		{ "Spawn of Hakkar", {} },
		{ "Troll Minibosses", {} },
		{ "Trash Mobs", {} },
	},

	["Uldaman"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Uldaman",
		Type = "ClassicDungeonExt",
		Map = "Uldaman",
		{ "Magregan Deepshadow", {} },
		{ "Tablet of Ryun'eh", {} },
		{ "Krom Stoutarm's Chest", {} },
		{ "Garrett Family Chest", {} },
		{ "Digmaster Shovelphlange", {} },
		{ "Baelog", {2060219} },
		{ "Revelosh", {} },
		{ "Ironaya", {2075372} },
		{ "Obsidian Sentinel", {2075372} },
		{ "Ancient Stone Keeper", {} },
		{ "Galgann Firehammer", {2060239} },
		{ "Tablet of Will", {} },
		{ "Shadowforge Cache", {} },
		{ "Grimlok", {2075109} },
		{ "Archaedas", {2074735} },
		{ "Trash Mobs", {} },
		{ "Ancient Stone Keeper", {} },
		{ "Archaedas", {} },
		{ "Baelog", {} },
		{ "Digmaster Shovelphlange", {} },
		{ "Galgann Firehammer", {} },
		{ "Grimlok", {} },
		{ "Ironaya", {} },
		{ "Obsidian Sentinel", {} },
		{ "Revelosh", {} },
		{ "Trash Mobs", {} },
	},

	["WailingCaverns"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Wailing Caverns",
		Type = "ClassicDungeonExt",
		Map = "WailingCaverns",
		{ "Kalldan Felmoon", {} },
		{ "Mad Magglish", {} },
		{ "Trigore the Lasher", {} },
		{ "Boahn", {} },
		{ "Lord Cobrahn", { 3669,2062556 } },
		{ "Lady Anacondra", { 3671,2063944 } },
		{ "Kresh", { 3653 } },
		{ "Lord Pythas", { 3670,2062557 } },
		{ "Skum", { 3674 } },
		{ "Lord Serpentis", { 3673,2061180 } },
		{ "Verdan the Everliving", { 5775 } },
		{ "Mutanus the Devourer", { 3654 } },
		{ "Deviate Faerie Dragon", {} },
		{ "Boahn", {} },
		{ "Deviate Faerie Dragon", {} },
		{ "Kresh", {} },
		{ "Lady Anacondra", {} },
		{ "Lord Cobrahn", {} },
		{ "Lord Pythas", {} },
		{ "Lord Serpentis", {} },
		{ "Mutanus the Devourer", {} },
		{ "Skum", {} },
		{ "Trigore the Lasher", {} },
		{ "Verdan the Everliving", {} },
	},

	["ZulFarrak"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Zul'Farrak",
		Type = "ClassicDungeonExt",
		Map = "ZulFarrak",
		{ "Antu'sul", {2062888} },
		{ "Theka the Martyr", { 7272,2061278 } },
		{ "Witch Doctor Zum'rah", {2060247} },
		{ "Nekrum Gutchewer", { 2060263,24081 } },
		{ "Shadowpriest Sezz'ziz", {2061261} },
		{ "Dustwraith", {2061348} },
		{ "Sergeant Bly", { 7604,2061258 } },
		{ "Sandfury Executioner", {} },
		{ "Hydromancer Velratha", { 2060262,24081 } },
		{ "Gahz'rilla", {} },
		{ "Chief Ukorz Sandscalp", {2061260} },
		{ "Zerillis", { 2060334,24081 } },
		{ "Trash Mobs", {} },
		{ "Antu'sul", {} },
		{ "Chief Ukorz Sandscalp", {} },
		{ "Dustwraith", {} },
		{ "Gahz'rilla", {} },
		{ "Hydromancer Velratha", {} },
		{ "Nekrum Gutchewer", {} },
		{ "Sergeant Bly", {} },
		{ "Shadowpriest Sezz'ziz", {} },
		{ "Theka the Martyr", {} },
		{ "Witch Doctor Zum'rah", {} },
		{ "Zerillis", {} },
		{ "Trash Mobs", {} },
	},

	["VaultsOfTheInquisition"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Vaults of the Inquisition",
		Type = "ClassicDungeonExt",
		{ "His Majesty Darkandle", { 162709 } },
		{ "Merciless Echo", { 162700 } },
		{ "The Deceiver's Presence", { 162704 } },
	},

	["RoadToDeOtherSide"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Road to De Other Side",
		Type = "ClassicDungeonExt",
		{ "Chimeric Embryo", { 162716 } },
		{ "Drak'math the Sinister King", { 162715 } },
		{ "Muzah, the Shadow Hunter", { 162711 } },
	},

	["SharedDungeonLoot"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Shared Dungeon Loot",
		Type = "ClassicDungeonExt",
		{ "Heroic", {} },
		{ "Mythic", {} },
		{ "Shared Dungeon Loot", {} },
		{ "Shared Dungeon Loot", {} },
		{ "Shared Dungeon Loot", {} },
	},

	["FrozenReach"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Frozen Reach",
		Type = "Manastorm",
		WebID = { 98888,"item" },
		{ "Frozen Reach", {} },
	},
})
