local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")

AtlasLoot:AddNewMenus({
	-- ClassicRaid
    ["ZulGurub"] = {
        Module = "AtlasLoot_OriginalWoW",
        Name = "Zul'Gurub",
        Type = "ClassicRaid",
        Map = "ZulGurub",
		{ "Bloodlord Mandokir", {} },
		{ "Gahz'ranka", {} },
		{ "Hakkar", {} },
		{ "High Priest Thekal", {} },
		{ "High Priest Venoxis", {} },
		{ "High Priestess Arlokk", {} },
		{ "High Priestess Jeklik", {} },
		{ "High Priestess Mar'li", {} },
		{ "Jin'do the Hexxer", {} },
		{ "Edge of Madness", {} },
		{ "Madness", {} },
		{ "Shared ZG Priest Drops", {} },
		{ "Zul'Gurub", {} },
		{ "Trash Mobs", {} },
		{ "Bijous & Coins", {} },
		{ "World Drops", {} },
    },

	["Onyxia60"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Onyxia's Lair",
		Type = "ClassicRaid",
		Map = "Onyxia60",
		{ "Basalthane", {} },
		{ "Onyxia", {} },
	},

	["RuinsofAQ"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Ruins of Ahn'Qiraj",
		Type = "ClassicRaid",
		Map = "TheRuinsofAhnQiraj",
		{ "Ayamiss the Hunter", {} },
		{ "Buru the Gorger", {} },
		{ "General Rajaxx", {} },
		{ "Kurinnaxx", {} },
		{ "Lieutenant General Andorov", {} },
		{ "Moam", {} },
		{ "Ossirian the Unscarred", {} },
		{ "Rajaxx's Captains", {} },
		{ "Trash Mobs", {} },
	},

	["TempleofAQ"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Temple of Ahn'Qiraj",
		Type = "ClassicRaid",
		Map = "TheTempleofAhnQiraj",
		{ "Battleguard Sartura", {} },
		{ "C'Thun", {} },
		{ "Fankriss the Unyielding", {} },
		{ "Ouro", {} },
		{ "Princess Huhuran", {} },
		{ "The Bug Family", {} },
		{ "The Prophet Skeram", {} },
		{ "The Twin Emperors", {} },
		{ "Viscidus", {} },
		{ "Trash Mobs", {} },
	},

	["AQOpening"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "AQOpening",
		{ "AQOpening", {} },
	},

	["Naxxramas60"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Naxxramas",
		Type = "ClassicRaid",
		Map = "Naxxramas60",
		{ "Anub'Rekhan", {} },
		{ "Gluth", {} },
		{ "Gothik the Harvester", {} },
		{ "Grand Widow Faerlina", {} },
		{ "Grobbulus", {} },
		{ "Heigan the Unclean", {} },
		{ "Instructor Razuvious", {} },
		{ "Kel'Thuzad", {} },
		{ "Loatheb", {} },
		{ "Maexxna", {} },
		{ "Naxxramas", {} },
		{ "Noth the Plaguebringer", {} },
		{ "Patchwerk", {} },
		{ "Sapphiron", {} },
		{ "Thaddius", {} },
		{ "The Four Horsemen", {} },
		{ "Trash Mobs", {} },
	},

	["WorldBossesCLASSIC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "World Bosses",
		Type = "ClassicRaid",
		{ "Azuregos", {6109} },
		{ "Lord Kazzak", {12397} },
		{ "Ysondre", {} },
		{ "Lethon", {} },
		{ "Emeriss", {} },
		{ "Taerar", {} },
		{ "Setis", {} },
		{ "Snowgrave", {} },
		{ "The Will of Soggoth", {} },
		{ "Atal'zul, the Soulreaver", {} },
		{ "Quest Items", {} },
	},

	-- ClassicDungeons
	["BlackfathomDeeps"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackfathom Deeps",
		Type = "ClassicDungeonExt",
		Map = "BlackfathomDeeps",
		{ "Aku'mai", {} },
		{ "Gelihast", {} },
		{ "Ghamoo-ra", {} },
		{ "Lady Sarevess", {} },
		{ "Old Serra'kis", {} },
		{ "Quest Item", {} },
		{ "Twilight Lord Kelris", {} },
		{ "Trash Mobs", {} },
	},

	["BlackrockDepths"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackrock Depths",
		Type = "ClassicDungeonExt",
		Map = "BlackrockDepths",
		{ "Ambassador Flamelash", {} },
		{ "Bael'Gar", {} },
		{ "Chest of The Seven", {} },
		{ "Dungeon Set 2 Summonable", {} },
		{ "Emperor Dagran Thaurissan", {} },
		{ "Fineous Darkvire", {} },
		{ "General Angerforge", {} },
		{ "Golem Lord Argelmach", {} },
		{ "High Interrogator Gerstahn", {} },
		{ "Houndmaster Grebmar", {} },
		{ "Hurley Blackbreath", {} },
		{ "Lord Incendius", {} },
		{ "Lord Roccor", {} },
		{ "Magmus", {} },
		{ "Panzor the Invincible (Rare)", {} },
		{ "Phalanx", {} },
		{ "Plugger Spazzring", {} },
		{ "Princess Moira Bronzebeard", {} },
		{ "Pyromancer Loregrain", {} },
		{ "Ribbly Screwspigot", {} },
		{ "Ring of Law", {} },
		{ "Shadowforge Flame Keeper", {} },
		{ "Summoner's Tomb", {} },
		{ "The Vault", {} },
		{ "Theldren", {} },
		{ "Verek", {} },
		{ "Warder Stilgiss", {} },
		{ "Trash Mobs", {} },
	},

	["BlackrockCavernsCLASSIC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackrock Caverns",
		Type = "ClassicDungeonExt",
		{ "Ascendant Lord Obsidius", {} },
		{ "Beauty", {} },
		{ "Corla, Herald of Twilight", {} },
		{ "Karsh Steelbender <Twilight Armorer>", {} },
		{ "Rom'ogg Bonecrusher", {} },
	},

	["LowerBlackrock"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Lower Blackrock Spire",
		Type = "ClassicDungeonExt",
		Loadfirst = 3,
		Map = "BlackrockSpire",
		{ "Bannok Grimaxe (Rare)", {} },
		{ "Burning Felguard (Rare, Random)", {} },
		{ "Crystal Fang", {} },
		{ "Ghok Bashguud (Rare)", {} },
		{ "Gizrul the Slavener", {} },
		{ "Halycon", {} },
		{ "Highlord Omokk", {} },
		{ "Mor Grayhoof (Summon)", {} },
		{ "Mother Smolderweb", {} },
		{ "Overlord Wyrmthalak", {} },
		{ "Quartermaster Zigris", {} },
		{ "Shadow Hunter Vosh'gajin", {} },
		{ "Spirestone Battle Lord (Rare)", {} },
		{ "Spirestone Butcher (Rare)", {} },
		{ "Spirestone Lord Magus (Rare)", {} },
		{ "Urok Doomhowl (Summon)", {} },
		{ "War Master Voone", {} },
	},

	["UpperBlackrock"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Upper Blackrock Spire",
		Type = "ClassicDungeonExt",
		Map = "BlackrockSpire",
		{ "Dungeon Set 2 Summonable", {} },
		{ "Father Flame", {} },
		{ "General Drakkisath", {} },
		{ "Goraluk Anvilcrack", {} },
		{ "Gyth", {} },
		{ "Jed Runewatcher", {} },
		{ "Lord Valthalak (Summon)", {} },
		{ "Pyroguard Emberseer", {} },
		{ "Solakar Flamewreath", {} },
		{ "The Beast", {} },
		{ "Unforged Rune Covered Breastplate", {} },
		{ "Warchief Rend Blackhand", {} },
	},

	["MoltenCore"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Molten Core",
		Type = "ClassicRaid",
		Map = "MoltenCore",
		{ "Lucifron", { 12118 } },
		{ "Magmadar", { 11982 } },
		{ "Gehennas", { 12259 } },
		{ "Garr", { 12057 } },
		{ "Baron Geddon", { 12056 } },
		{ "Shazzrah", { 12264 } },
		{ "Golemagg the Incinerator", { 11988 } },
		{ "Sulfuron Harbinger", { 12098 } },
		{ "Majordomo Executus", { 12018 } },
		{ "Ragnaros", { 11502 } },
		{ "Molten Core", {} },
		{ "Random Boss Drops", {} },
		{ "Trash Mobs", {} },
	},

	["BlackwingLair"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackwing Lair",
		Type = "ClassicRaid",
		Map = "BlackwingLair",
		{ "Blackwing Lair", {} },
		{ "Broodlord Lashlayer", {} },
		{ "Chromaggus", {} },
		{ "Ebonroc", {} },
		{ "Firemaw", {} },
		{ "Flamegor", {} },
		{ "Nefarian", {} },
		{ "Razorgore the Untamed", {} },
		{ "Vaelastrasz the Corrupt", {} },
		{ "Trash Mobs", {} },
	},

	["DireMaulEast"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul East",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		MapNum = 5,
		{ "Alzzin the Wildshaper", {} },
		{ "Dungeon Set 2 Summonable", {} },
		{ "Hydrospawn", {} },
		{ "Isalien", {} },
		{ "Lethtendris", {} },
		{ "Pimgib", {} },
		{ "Zevrim Thornhoof", {} },
		{ "Trash Mobs", {} },
	},

	["DireMaulNorth"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul North",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		MapNum = 1,
		{ "Captain Kromcrush", {} },
		{ "Cho'Rush the Observer", {} },
		{ "DM North Tribute Chest", {} },
		{ "Fengus's Chest", {} },
		{ "Guard Fengus", {} },
		{ "Guard Mol'dar", {} },
		{ "Guard Slip'kik", {} },
		{ "King Gordok", {} },
		{ "Ogre Tannin Basket", {} },
		{ "Stomper Kreeg", {} },
	},

	["DireMaulWest"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul West",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		MapNum = 2,
		{ "Illyanna Ravenoak", {} },
		{ "Immol'thar", {} },
		{ "Lord Hel'nurath", {} },
		{ "Magister Kalendris", {} },
		{ "Prince Tortheldrin", {} },
		{ "Tendris Warpwood", {} },
		{ "The Prince's Chest", {} },
		{ "Tsu'zee", {} },
		{ "Trash Mobs", {} },
	},

	["Gnomeregan"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Gnomeregan",
		Type = "ClassicDungeonExt",
		Map = "Gnomeregan",
		{ "Crowd Pummeler 9-60", {} },
		{ "Dark Iron Ambassador", {} },
		{ "Electrocutioner 6000", {} },
		{ "Grubbis", {} },
		{ "Mekgineer Thermaplugg", {} },
		{ "Techbot", {} },
		{ "Viscous Fallout", {} },
		{ "Trash Mobs", {} },
	},

	["KarazhanCrypts"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Karazhan Crypts",
		Type = "ClassicDungeonExt",
		{ "Cynfael", {}, WebID = {254401,"npc"} },
		{ "Dryn Miel <The Second Eidolon>", {}, WebID =  {254413,"npc"} },
		{ "Kurgoth Doomreaver", {}, WebID = {254406,"npc"} },
		{ "The Judgement of Sinners",  {}, WebID =  {254405,"npc"} },
		{ "Captain Taveir (Rare Spawn)",  {}, WebID =  {254495,"npc"} },
		{ "Kelivex Autumnvale (Rare Spawn)",  {}, WebID =  {254493,"npc"} },
	},

	["Maraudon"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Maraudon",
		Type = "ClassicDungeonExt",
		Map = "Maraudon",
		{ "Celebras the Cursed", {} },
		{ "Landslide", {} },
		{ "Lord Vyletongue", {} },
		{ "Meshlok the Harvester", {} },
		{ "Noxxion", {} },
		{ "Princess Theradras", {} },
		{ "Razorlash", {} },
		{ "Rotgrip", {} },
		{ "Tinkerer Gizlock", {} },
	},

	["RagefireChasm"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Ragefire Chasm",
		Type = "ClassicDungeonExt",
		Map = "RagefireChasm",
		{ "Jergosh the Invoker", {} },
		{ "Oggleflint", {} },
		{ "Taragaman the Hungerer", {} },
		{ "Zelemar the Wrathful", {} },
	},

	["RazorfenDowns"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Razorfen Downs",
		Type = "ClassicDungeonExt",
		Map = "RazorfenDowns",
		{ "Amnennar the Coldbringer", {} },
		{ "Glutton", {} },
		{ "Lady Falther'ess", {} },
		{ "Mordresh Fire Eye", {} },
		{ "Plaguemaw the Rotting", {} },
		{ "Ragglesnout", {} },
		{ "Tuten'kash", {} },
		{ "Trash Mobs", {} },
	},

	["RazorfenKraul"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Razorfen Kraul",
		Type = "ClassicDungeonExt",
		Map = "RazorfenKraul",
		{ "Agathelos the Raging", {} },
		{ "Aggem Thorncurse", {} },
		{ "Blind Hunter", {} },
		{ "Charlga Razorflank", {} },
		{ "Death Speaker Jargba", {} },
		{ "Earthcaller Halmgar", {} },
		{ "Overlord Ramtusk", {} },
		{ "Razorfen Spearhide", {} },
		{ "Roogug", {} },
		{ "Trash Mobs", {} },
	},

	["ScarletMonasteryArmory"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Armory",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 3,
		{ "Herod", {} },
		{ "Trash Mobs", {} },
	},

	["ScarletMonasteryCathedral"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Cathedral",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 4,
		{ "High Inquisitor Whitemane", {} },
		{ "Scarlet Commander Mograine", {} },
	},

	["ScarletMonasteryGraveyard"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Graveyard",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 1,
		{ "Azshir the Sleepless", {} },
		{ "Bloodmage Thalnos", {} },
		{ "Fallen Champion", {} },
		{ "Ironspine", {} },
	},

	["ScarletMonasteryLibrary"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery Library",
		Type = "ClassicDungeonExt",
		Map = "ScarletMonastery",
		MapNum = 2,
		{ "Arcanist Doan", {} },
		{ "Doan's Strongbox", {} },
	},

	["Scholomance"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scholomance",
		Type = "ClassicDungeonExt",
		Loadfirst = 3,
		Map = "Scholomance",
		{ "Darkmaster Gandling", {} },
		{ "Death Knight Darkreaver", {} },
		{ "Doctor Theolen Krastinov", {} },
		{ "Dungeon Set 2 Summonable", {} },
		{ "Frostwhisper's Embalming Fluid", {} },
		{ "Instructor Malicia", {} },
		{ "Jandice Barov", {} },
		{ "Kirtonos the Herald", {} },
		{ "Kormok", {} },
		{ "Lady Illucia Barov", {} },
		{ "Lord Alexei Barov", {} },
		{ "Lorekeeper Polkelt", {} },
		{ "Marduk Blackpool", {} },
		{ "Ras Frostwhisper", {} },
		{ "Rattlegore", {} },
		{ "Vectus", {} },
		{ "Trash Mobs", {} },
	},

	["ShadowfangKeep"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Shadowfang Keep",
		Type = "ClassicDungeonExt",
		Map = "ShadowfangKeep",
		{ "Apothecary Hummel", {} },
		{ "Archmage Arugal", {} },
		{ "Baron Silverlaine", {} },
		{ "Commander Springvale", {} },
		{ "Deathsworn Captain", {} },
		{ "Fenrus the Devourer", {} },
		{ "Odo the Blindwatcher", {} },
		{ "Razorclaw the Butcher", {} },
		{ "Rethilgore", {} },
		{ "Wolf Master Nandos", {} },
		{ "Trash Mobs", {} },
	},

	["Stratholme"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Stratholme",
		Type = "ClassicDungeonExt",
		Map = "Stratholme",
		{ "Archivist Galford", {} },
		{ "Balnazzar", {} },
		{ "Baron Rivendare", {} },
		{ "Baroness Anastari", {} },
		{ "Cannon Master Willey", {} },
		{ "Dungeon Set 2 Summonable", {} },
		{ "Hearthsinger Forresten", {} },
		{ "Magistrate Barthilas", {} },
		{ "Maleki the Pallid", {} },
		{ "Malor's Strongbox", {} },
		{ "Nerub'enkan", {} },
		{ "Ramstein the Gorger", {} },
		{ "Skul", {} },
		{ "Sothos and Jarien", {} },
		{ "Stonespine", {} },
		{ "The Unforgiven", {} },
		{ "Timmy the Cruel", {} },
		{ "Unfinished Painting", {} },
		{ "Trash Mobs", {} },
	},

	["TheDeadmines"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Deadmines",
		Type = "ClassicDungeonExt",
		Map = "TheDeadmines",
		{ "Brainwashed Noble", {} },
		{ "Captain Greenskin", {} },
		{ "Cookie", {} },
		{ "Edwin VanCleef", {} },
		{ "Gilnid", {} },
		{ "Marisa du'Paige", {} },
		{ "Miner Johnson", {} },
		{ "Mr. Smite", {} },
		{ "Rhahk'Zor", {} },
		{ "Sneed", {} },
		{ "Sneed's Shredder", {} },
	},

	["TheStockade"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Stockade",
		Type = "ClassicDungeonExt",
		Map = "TheStockade",
		{ "Bazil Thredd", {} },
		{ "Bruegal Ironknuckle", {} },
		{ "Dextren Ward", {} },
		{ "Hamhock", {} },
		{ "Kam Deepfury", {} },
		{ "Targorr the Dread", {} },
	},

	["SunkenTemple"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Sunken Temple",
		Type = "ClassicDungeonExt",
		Map = "TheSunkenTemple",
		{ "Atal'alarion", {} },
		{ "Avatar of Hakkar", {} },
		{ "Hazzas", {} },
		{ "Jammal'an the Prophet", {} },
		{ "Ogom the Wretched", {} },
		{ "Shade of Eranikus", {} },
		{ "Spawn of Hakkar", {} },
		{ "Troll Minibosses", {} },
		{ "Trash Mobs", {} },
	},

	["Uldaman"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Uldaman",
		Type = "ClassicDungeonExt",
		Map = "Uldaman",
		{ "Ancient Stone Keeper", {} },
		{ "Archaedas", {} },
		{ "Baelog", {} },
		{ "Digmaster Shovelphlange", {} },
		{ "Galgann Firehammer", {} },
		{ "Grimlok", {} },
		{ "Ironaya", {} },
		{ "Obsidian Sentinel", {} },
		{ "Revelosh", {} },
		{ "Trash Mobs", {} },
	},

	["WailingCaverns"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Wailing Caverns",
		Type = "ClassicDungeonExt",
		Map = "WailingCaverns",
		{ "Boahn", {} },
		{ "Deviate Faerie Dragon", {} },
		{ "Kresh", {} },
		{ "Lady Anacondra", {} },
		{ "Lord Cobrahn", {} },
		{ "Lord Pythas", {} },
		{ "Lord Serpentis", {} },
		{ "Mutanus the Devourer", {} },
		{ "Skum", {} },
		{ "Trigore the Lasher", {} },
		{ "Verdan the Everliving", {} },
	},

	["ZulFarrak"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Zul'Farrak",
		Type = "ClassicDungeonExt",
		Map = "ZulFarrak",
		{ "Antu'sul", {} },
		{ "Chief Ukorz Sandscalp", {} },
		{ "Dustwraith", {} },
		{ "Gahz'rilla", {} },
		{ "Hydromancer Velratha", {} },
		{ "Nekrum Gutchewer", {} },
		{ "Sergeant Bly", {} },
		{ "Shadowpriest Sezz'ziz", {} },
		{ "Theka the Martyr", {} },
		{ "Witch Doctor Zum'rah", {} },
		{ "Zerillis", {} },
		{ "Trash Mobs", {} },
	},

	["VaultsOfTheInquisition"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Vaults of the Inquisition",
		Type = "ClassicDungeonExt",
		{ "His Majesty Darkandle", { 162709 } },
		{ "Merciless Echo", { 162700 } },
		{ "The Deceiver's Presence", { 162704 } },
	},

	["RoadToDeOtherSide"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Road to De Other Side",
		Type = "ClassicDungeonExt",
		{ "Chimeric Embryo", { 162716 } },
		{ "Drak'math the Sinister King", { 162715 } },
		{ "Muzah, the Shadow Hunter", { 162711 } },
	},

	["SharedDungeonLoot"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Shared Dungeon Loot",
		Type = "ClassicDungeonExt",
		{ "Heroic", {} },
		{ "Mythic", {} },
		{ "Shared Dungeon Loot", {} },
		{ "Shared Dungeon Loot", {} },
		{ "Shared Dungeon Loot", {} },
	},

	["FrozenReach"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Frozen Reach",
		Type = "Manastorm",
		WebID = { 98888,"item" },
		{ "Frozen Reach", {} },
	},
})
