local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")
-- Generated by bisbeard/convert_mystic_enchants.py. Do not edit by hand.
AtlasLoot:AddNewMenus({
	["MysticEnchantsDruid"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Druid",
		{ "Druid", {} },
	},
	["MysticEnchantsHunter"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Hunter",
		{ "Hunter", {} },
	},
	["MysticEnchantsMage"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Mage",
		{ "Mage", {} },
	},
	["MysticEnchantsPaladin"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Paladin",
		{ "Paladin", {} },
	},
	["MysticEnchantsPriest"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Priest",
		{ "Priest", {} },
	},
	["MysticEnchantsRogue"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Rogue",
		{ "Rogue", {} },
	},
	["MysticEnchantsShaman"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Shaman",
		{ "Shaman", {} },
	},
	["MysticEnchantsWarlock"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Warlock",
		{ "Warlock", {} },
	},
	["MysticEnchantsWarrior"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Warrior",
		{ "Warrior", {} },
	},
})
