local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")
-- Generated by bisbeard/convert_mystic_enchants.py. Do not edit by
-- hand: re-run the script after refreshing raw/lootcollector_bronzebeard.json.
AtlasLoot:AddItemData("dontSort", {
	["MysticEnchantsDruid"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 201374, desc = "Stranglethorn Vale (39, 34)" }, --Ambush Predator
			{ itemID = 201498, desc = "Silverpine Forest (44, 42)" }, --Astral Alignment
			{ itemID = 202587, desc = "Silithus (63, 51)" }, --Astral Winds
			{ itemID = 1013887, desc = "Stranglethorn Vale (38, 3)" }, --Balance Mastery
			{ itemID = 201054, desc = "Western Plaguelands (59, 51)" }, --Bash and Thrash
			{ itemID = 200529, desc = "Feralas (57, 62)" }, --Blooming Power
			{ itemID = 1013744, desc = "Razorfen Kraul (58, 30)" }, --Brambles
			{ itemID = 200262, desc = "Ashenvale (86, 45)" }, --Carnage Incarnate
			{ itemID = 1013749, desc = "Feralas (67, 47)" }, --Celestial Focus
			{ itemID = 200722, desc = "Winterspring (64, 23)" }, --Celestial Replenishment
			{ itemID = 201044, desc = "Moonglade (71, 56)" }, --Critical Cycles
			{ itemID = 201139, desc = "Un'Goro Crater (28, 62)" }, --Cycles of Growth
			{ itemID = 200888, desc = "Felwood (35, 53)" }, --Deranged Druid
			{ itemID = 201170, desc = "Feralas (76, 42)" }, --Earthen Power Well
			{ itemID = 1300147, desc = "Feralas (56, 50)" }, --Efflorescence
			{ itemID = 200785, desc = "Wailing Caverns (68, 37)" }, --Faerie's Favor
			{ itemID = 1013746, desc = "Azshara (41, 53)" }, --Feral Aggression
			{ itemID = 200846, desc = "Feralas (76, 42)" }, --Feral Frenzy
			{ itemID = 1013753, desc = "Stonetalon Mountains (30, 18)" }, --Feral Instinct
			{ itemID = 1013884, desc = "Feralas (67, 48)" }, --Feral Mastery
			{ itemID = 1013843, desc = "Feralas (69, 39)" }, --Feral Swiftness
			{ itemID = 201552, desc = "Ashenvale (62, 51)" }, --Ferocious Clarity
			{ itemID = 1013751, desc = "Blackrock Depths (57, 86)" }, --Ferocity
			{ itemID = 200798, desc = "Redridge Mountains (24, 42)" }, --Flourishing Nourish
			{ itemID = 201256, desc = "Stranglethorn Vale (28, 41)" }, --Flow of Life
			{ itemID = 201332, desc = "Un'Goro Crater (68, 31)" }, --Frenzied Growth
			{ itemID = 201599, desc = "Darkshore (42, 36)" }, --Frenzied Slashing
			{ itemID = 1013758, desc = "Ashenvale (62, 51)" }, --Furor
			{ itemID = 1013970, desc = "Silithus (60, 54)" }, --Genesis
			{ itemID = 201572, desc = "Tanaris (82, 90)" }, --Graceful Resurgence
			{ itemID = 1013885, desc = "Hillsbrad Foothills (85, 32)" }, --Guardian Mastery
			{ itemID = 200858, desc = "Tanaris (52, 29)" }, --Guardians of the Grove
			{ itemID = 1013757 }, --Improved Mark of the Wild
			{ itemID = 1013742, desc = "Winterspring (65, 61)" }, --Improved Moonfire
			{ itemID = 1013762, desc = "Wailing Caverns (76, 43)" }, --Improved Rejuvenation
			{ itemID = 200867, desc = "Stranglethorn Vale (42, 15)" }, --Incarnation: King of the Jungle
			{ itemID = 1013761, desc = "Redridge Mountains (76, 47)" }, --Intensity
			{ itemID = 200074, desc = "Darkshore (38, 42)" }, --Ironfur
			{ itemID = 1013604, desc = "Silithus (61, 54)" }, --Languish
			{ itemID = 200457, desc = "Feralas (33, 65)" }, --Localized Storm
			{ itemID = 200088, desc = "Stranglethorn Vale (45, 24)" }, --Mass Entanglement
			{ itemID = 1013915, desc = "Feralas (76, 42)" }, --Master Shapeshifter
			{ itemID = 201515, desc = "The Barrens (48, 86)" }, --Moon's Wrath
			{ itemID = 1013745, desc = "Dire Maul (31, 37)" }, --Moonglow
			{ itemID = 1013743, desc = "Feralas (67, 48)" }, --Natural Shapeshifter
			{ itemID = 1013760, desc = "Winterspring (68, 38)" }, --Naturalist
			{ itemID = 201518, desc = "The Barrens (44, 23)" }, --Nature's Abundance
			{ itemID = 200868, desc = "Feralas (39, 65)" }, --Nature's Fervor
			{ itemID = 1013759, desc = "Felwood (58, 18)" }, --Nature's Focus
			{ itemID = 1013978, desc = "Ragefire Chasm (66, 63)" }, --Nature's Grace
			{ itemID = 1013901, desc = "Feralas (69, 39)" }, --Nature's Majesty
			{ itemID = 1013741, desc = "The Hinterlands (31, 48)" }, --Nature's Reach
			{ itemID = 1013971, desc = "Wailing Caverns (78, 30)" }, --Nature's Splendor
			{ itemID = 1013600, desc = "Swamp of Sorrows (71, 67)" }, --Nature's Synthesis
			{ itemID = 1013747, desc = "Tirisfal Glades (77, 46)" }, --Omen of Clarity
			{ itemID = 200816, desc = "Duskwood (45, 38)" }, --Omen of Doom
			{ itemID = 200613, desc = "Tanaris (52, 28)" }, --Overflow
			{ itemID = 201356, desc = "Ashenvale (88, 44)" }, --Predator's Wrath: Combo
			{ itemID = 200630, desc = "Darkshore (43, 68)" }, --Predator's Wrath: Focus
			{ itemID = 200908, desc = "Desolace (66, 7)" }, --Predator's Wrath: Wrathful Strikes
			{ itemID = 1013755, desc = "Tanaris (28, 63)" }, --Predatory Strikes
			{ itemID = 201219, desc = "Stranglethorn Vale (38, 38)" }, --Primal Frenzy
			{ itemID = 1013907, desc = "Zul'Gurub (57, 52)" }, --Primal Fury
			{ itemID = 201116, desc = "Winterspring (54, 18)" }, --Razor-sharp Claws
			{ itemID = 201133, desc = "Ashenvale (84, 48)" }, --Relentless Laceration
			{ itemID = 200817, desc = "Winterspring (35, 45)" }, --Savage Barricade
			{ itemID = 1013756, desc = "Zul'Gurub (47, 21)" }, --Savage Fury
			{ itemID = 200836, desc = "Feralas (55, 75)" }, --Shifting Bark
			{ itemID = 1013754, desc = "The Hinterlands (42, 65)" }, --Shredding Attacks
			{ itemID = 200100, desc = "Azshara (38, 36)" }, --Solar Beam
			{ itemID = 200352, desc = "Moonglade (52, 71)" }, --Spirit of the Forest
			{ itemID = 200089, desc = "Hillsbrad Foothills (95, 16)" }, --Stampeding Roar
			{ itemID = 1013740, desc = "Dire Maul (13, 58)" }, --Starlight Wrath
			{ itemID = 202552, desc = "Azshara (49, 49)" }, --Stellar Convergence
			{ itemID = 202578, desc = "Moonglade (40, 58)" }, --Stonebark
			{ itemID = 1013763, desc = "Ashenvale (12, 26)" }, --Subtlety
			{ itemID = 200353, desc = "Redridge Mountains (31, 47)" }, --Sunfire
			{ itemID = 1013610, desc = "Moonglade (53, 42)" }, --Surging Eclipse
			{ itemID = 201546, desc = "Teldrassil (58, 57)" }, --Symbiotic Nature
			{ itemID = 201598, desc = "Ashenvale (65, 69)" }, --Tiger's Instinct
			{ itemID = 201080, desc = "Azshara (28, 51)" }, --TIMBERRR
			{ itemID = 200845, desc = "Feralas (60, 46)" }, --Touch of Elune
			{ itemID = 1013844, desc = "Wailing Caverns (81, 55)" }, --Tranquil Spirit
			{ itemID = 201375, desc = "Alterac Mountains (52, 69)" }, --Ursoc's Rage
			{ itemID = 200087, desc = "Azshara (35, 49)" }, --Ursol's Vortex
			{ itemID = 1013748, desc = "Arathi Highlands (27, 59)" }, --Vengeance
			{ itemID = 201545, desc = "Maraudon (37, 26)" }, --Verdant Insight
			{ itemID = 11880, desc = "Western Plaguelands (35, 64)" }, --Viscera
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554209 }, --Glyph of Berserk
			{ itemID = 554274, desc = "Stranglethorn Vale (36, 10)" }, --Glyph of Claw
			{ itemID = 554005, desc = "Silverpine Forest (77, 22)" }, --Glyph of Entangling Roots
			{ itemID = 554206 }, --Glyph of Focus
			{ itemID = 554013, desc = "Westfall (36, 37)" }, --Glyph of Healing Touch
			{ itemID = 554017 }, --Glyph of Hurricane
			{ itemID = 554018 }, --Glyph of Innervate
			{ itemID = 554016 }, --Glyph of Insect Swarm
			{ itemID = 554014 }, --Glyph of Lifebloom
			{ itemID = 554008 }, --Glyph of Mangle
			{ itemID = 554007, desc = "Coldridge Valley (70, 60)" }, --Glyph of Maul
			{ itemID = 554213, desc = "Feralas (76, 42)" }, --Glyph of Monsoon
			{ itemID = 554020, desc = "Winterspring (64, 59)" }, --Glyph of Moonfire
			{ itemID = 554211 }, --Glyph of Nourish
			{ itemID = 554011, desc = "Zul'Gurub (59, 42)" }, --Glyph of Rake
			{ itemID = 554277, desc = "Winterspring (64, 21)" }, --Glyph of Rapid Rejuvenation
			{ itemID = 554001, desc = "Feralas (76, 42)" }, --Glyph of Rebirth
			{ itemID = 554002, desc = "Feralas (70, 44)" }, --Glyph of Regrowth
			{ itemID = 554003, desc = "Stonetalon Mountains (35, 12)" }, --Glyph of Rejuvenation
			{ itemID = 554010, desc = "Winterspring (51, 9)" }, --Glyph of Rip
			{ itemID = 554212 }, --Glyph of Savage Roar
			{ itemID = 554009, desc = "Silverpine Forest (66, 13)" }, --Glyph of Shred
			{ itemID = 554015 }, --Glyph of Starfall
			{ itemID = 554019, desc = "Winterspring (65, 61)" }, --Glyph of Starfire
			{ itemID = 554273 }, --Glyph of Survival Instincts
			{ itemID = 554012, desc = "Stonetalon Mountains (35, 12)" }, --Glyph of Swiftmend
			{ itemID = 201495, desc = "Feralas (76, 42)" }, --Glyph of Typhoon
			{ itemID = 554004, desc = "Desolace (53, 29)" }, --Glyph of Wrath
		},
	},
	["MysticEnchantsHunter"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 200154, desc = "Mulgore (48, 56)" }, --Aimed Shot
			{ itemID = 202596, desc = "Un'Goro Crater (43, 7)" }, --Apex Predator
			{ itemID = 1013949 }, --Aspect Mastery
			{ itemID = 1013909, desc = "Arathi Highlands (71, 81)" }, --Aspect of the Fox
			{ itemID = 201472, desc = "Redridge Mountains (29, 48)" }, --Barbed Shot
			{ itemID = 201468, desc = "Feralas (70, 36)" }, --Beastmaster's Gambit
			{ itemID = 1013893, desc = "Western Plaguelands (43, 84)" }, --Beastmastery Mastery
			{ itemID = 554405, desc = "Silithus (39, 75)" }, --Black Widow Strike
			{ itemID = 200949, desc = "Stranglethorn Vale (40, 17)" }, --Blood Tracker: Carving Strikes
			{ itemID = 200544, desc = "Silithus (49, 37)" }, --Blood Tracker: Deadly Bite
			{ itemID = 1013868 }, --Careful Aim
			{ itemID = 201107, desc = "Eastern Plaguelands (53, 23)" }, --Charged Up
			{ itemID = 201019, desc = "Teldrassil (57, 55)" }, --Combat Rhythm
			{ itemID = 201589, desc = "Redridge Mountains (89, 68)" }, --Concussive Trauma
			{ itemID = 200543, desc = "Alterac Mountains (54, 20)" }, --Deadly Instinct
			{ itemID = 1013908, desc = "Alterac Mountains (81, 51)" }, --Defense of the Turtle
			{ itemID = 1013800, desc = "Swamp of Sorrows (57, 25)" }, --Deflection
			{ itemID = 1013803, desc = "Gnomeregan (25, 43)" }, --Efficiency
			{ itemID = 201191, desc = "Swamp of Sorrows (56, 58)" }, --Expunge
			{ itemID = 1013816, desc = "Stranglethorn Vale (28, 13)" }, --Ferocity
			{ itemID = 1013910, desc = "Western Plaguelands (57, 36)" }, --Flanking Strike
			{ itemID = 200343, desc = "Redridge Mountains (30, 48)" }, --Flare Strike
			{ itemID = 1013952, desc = "Palemane Rock (66, 19)" }, --Focused Aim
			{ itemID = 1013900, desc = "Blackrock Depths (52, 93)" }, --Focused Fire
			{ itemID = 1013871, desc = "Elwynn Forest (41, 66)" }, --Go for the Throat
			{ itemID = 1013809, desc = "Gnomeregan (46, 70)" }, --Hawk Eye
			{ itemID = 201555, desc = "Northshire Valley (33, 53)" }, --Hunting Frenzy
			{ itemID = 1013810, desc = "Zul'Gurub (44, 51)" }, --Improved Aspect of the Monkey
			{ itemID = 1013802, desc = "Eastern Plaguelands (48, 15)" }, --Improved Concussive Shot
			{ itemID = 1013813, desc = "Shadowfang Keep (37, 59)" }, --Improved Mend Pet
			{ itemID = 1013807, desc = "Zul'Gurub (54, 29)" }, --Improved Stings
			{ itemID = 1013947, desc = "Stranglethorn Vale (31, 29)" }, --Improved Tracking
			{ itemID = 200979, desc = "Stranglethorn Vale (26, 12)" }, --Joint Onslaught
			{ itemID = 201476, desc = "Stonetalon Mountains (33, 65)" }, --Kindle for the Fire
			{ itemID = 202595, desc = "Un'Goro Crater (43, 7)" }, --Laceration
			{ itemID = 1013805, desc = "Elwynn Forest (41, 66)" }, --Lethal Shots
			{ itemID = 1013968, desc = "Blackrock Depths (39, 80)" }, --Lock and Load
			{ itemID = 200708, desc = "Silverpine Forest (59, 8)" }, --Lone Wolf
			{ itemID = 201586, desc = "Dun Morogh (62, 58)" }, --Marked Detonation
			{ itemID = 1013891, desc = "Eastern Plaguelands (48, 14)" }, --Marksmanship Mastery
			{ itemID = 201469, desc = "Searing Gorge (48, 66)" }, --Molten Ammo
			{ itemID = 1013808, desc = "Elwynn Forest (41, 66)" }, --Mortal Shots
			{ itemID = 200674, desc = "Scarlet Monastery (65, 85)" }, --Power Through
			{ itemID = 200993, desc = "Alterac Mountains (45, 79)" }, --Powershot
			{ itemID = 200318, desc = "The Hinterlands (35, 48)" }, --Rain of Arrows
			{ itemID = 1013870, desc = "Blackrock Depths (38, 76)" }, --Rapid Killing
			{ itemID = 200950, desc = "Western Plaguelands (52, 45)" }, --Savage Momentum
			{ itemID = 201040, desc = "Desolace (71, 69)" }, --Spot Weakness
			{ itemID = 201568, desc = "Redridge Mountains (30, 84)" }, --Stalker's Mark
			{ itemID = 200981, desc = "Eastern Plaguelands (23, 68)" }, --Steady Pace
			{ itemID = 201547, desc = "Stranglethorn Vale (36, 11)" }, --Steady Shooting
			{ itemID = 202597, desc = "Un'Goro Crater (43, 7)" }, --Sting Specialist
			{ itemID = 1013869, desc = "Scarlet Monastery (23, 51)" }, --Survival Instincts
			{ itemID = 1013892, desc = "Darkshore (37, 44)" }, --Survival Mastery
			{ itemID = 1013799 }, --Survival Tactics
			{ itemID = 1013967, desc = "The Hinterlands (29, 46)" }, --T.N.T.
			{ itemID = 1013817, desc = "Stranglethorn Vale (31, 29)" }, --Thick Hide
			{ itemID = 200396, desc = "Stranglethorn Vale (43, 20)" }, --Trap Launcher
			{ itemID = 201275, desc = "The Hinterlands (30, 49)" }, --Trick Shots
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554145, desc = "Stranglethorn Vale (31, 29)" }, --Glyph of Aimed Shot
			{ itemID = 554154 }, --Glyph of Arcane Shot
			{ itemID = 554149, desc = "Desolace (53, 29)" }, --Glyph of Bestial Wrath
			{ itemID = 554216, desc = "Scarlet Monastery (30, 78)" }, --Glyph of Explosive Shot
			{ itemID = 554218, desc = "Dun Morogh (46, 53)" }, --Glyph of Explosive Trap
			{ itemID = 554148 }, --Glyph of Hunter's Mark
			{ itemID = 554217 }, --Glyph of Kill Shot
			{ itemID = 554151, desc = "Dun Morogh (27, 38)" }, --Glyph of Mending
			{ itemID = 554152, desc = "Elwynn Forest (41, 66)" }, --Glyph of Multi-Shot
			{ itemID = 200076, desc = "Stranglethorn Vale (31, 29)" }, --Glyph of Quick Shot
			{ itemID = 554220, desc = "Teldrassil (58, 58)" }, --Glyph of Raptor Strike
			{ itemID = 554150, desc = "Stranglethorn Vale (31, 29)" }, --Glyph of Serpent Sting
			{ itemID = 554146 }, --Glyph of Steady Shot
			{ itemID = 554163 }, --Glyph of the Hawk
			{ itemID = 554159, desc = "Zul'Gurub (48, 21)" }, --Glyph of Wyvern Sting
		},
	},
	["MysticEnchantsMage"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 201296, desc = "Alterac Mountains (14, 57)" }, --Abjurer's Ward: Arcane
			{ itemID = 201297, desc = "Un'Goro Crater (48, 44)" }, --Abjurer's Ward: Fire
			{ itemID = 201298, desc = "Azshara (68, 91)" }, --Abjurer's Ward: Frost
			{ itemID = 201595, desc = "Duskwood (20, 54)" }, --Arcane Cascade
			{ itemID = 1013624, desc = "Alterac Mountains (21, 86)" }, --Arcane Concentration
			{ itemID = 202592, desc = "Desolace (39, 25)" }, --Arcane Conduit
			{ itemID = 201528, desc = "Redridge Mountains (88, 73)" }, --Arcane Dominance
			{ itemID = 1013643, desc = "Stratholme (63, 66)" }, --Arcane Focus
			{ itemID = 1013955 }, --Arcane Fortitude
			{ itemID = 1013874, desc = "Alterac Mountains (13, 78)" }, --Arcane Mastery
			{ itemID = 1013785 }, --Arcane Meditation
			{ itemID = 200126, desc = "Azshara (37, 59)" }, --Arcane Orb
			{ itemID = 201173, desc = "Elwynn Forest (44, 67)" }, --Arcane Power Well
			{ itemID = 1013627 }, --Arcane Shielding
			{ itemID = 1013739, desc = "Blackrock Spire (44, 60)" }, --Arcane Stability
			{ itemID = 1013625, desc = "Searing Gorge (31, 61)" }, --Arcane Subtlety
			{ itemID = 201171, desc = "Desolace (42, 19)" }, --Arctic Power Well
			{ itemID = 1013737, desc = "Wetlands (63, 67)" }, --Arctic Reach
			{ itemID = 201446, desc = "Azshara (71, 91)" }, --Barrage Overload
			{ itemID = 201583, desc = "Dun Morogh (47, 52)" }, --Biting Frost
			{ itemID = 201373, desc = "Dustwallow Marsh (51, 77)" }, --Brand of the Pyromaniac
			{ itemID = 1013616, desc = "Zul'Gurub (58, 34)" }, --Burning Soul
			{ itemID = 1013982, desc = "Dustwallow Marsh (38, 68)" }, --Cremation
			{ itemID = 200729, desc = "Burning Steppes (76, 56)" }, --Critical Time
			{ itemID = 1013611, desc = "Burning Steppes (32, 61)" }, --Draconic Knowledge
			{ itemID = 201467, desc = "Stranglethorn Vale (21, 23)" }, --Elemental Torrent
			{ itemID = 1013872, desc = "Dustwallow Marsh (64, 28)" }, --Fire Mastery
			{ itemID = 201195, desc = "Stranglethorn Vale (50, 29)" }, --Fire Walk With Me
			{ itemID = 201231, desc = "The Deadmines (Entrance) (58, 63)" }, --Fired Up
			{ itemID = 201534, desc = "Wetlands (67, 46)" }, --Flame Alignment
			{ itemID = 1013617, desc = "Burning Steppes (22, 46)" }, --Flame Throwing
			{ itemID = 200388, desc = "Eastern Plaguelands (74, 75)" }, --Focal Point
			{ itemID = 200163 }, --Focus Magic
			{ itemID = 200181, desc = "Winterspring (47, 40)" }, --Frost Bomb
			{ itemID = 1013622 }, --Frost Channeling
			{ itemID = 1013873, desc = "Scarlet Monastery (25, 56)" }, --Frost Mastery
			{ itemID = 1013853, desc = "Blackrock Depths (59, 64)" }, --Frost Warding
			{ itemID = 1013621 }, --Frostbite
			{ itemID = 201158, desc = "Feralas (58, 45)" }, --Frozen Flesh
			{ itemID = 200513, desc = "Alterac Mountains (38, 40)" }, --Frozen Haste
			{ itemID = 200063, desc = "Alterac Mountains (33, 62)" }, --Frozen Orb
			{ itemID = 200735, desc = "Silverpine Forest (46, 68)" }, --Glacial Cascade
			{ itemID = 200547, desc = "Molten Core (48, 75)" }, --Ice Barrage
			{ itemID = 1013959, desc = "Gnomeregan (37, 72)" }, --Ice Floes
			{ itemID = 1013699, desc = "Hillsbrad Foothills (15, 78)" }, --Ice Shards
			{ itemID = 201543, desc = "Wetlands (45, 33)" }, --Icy Slaughter
			{ itemID = 200142 }, --Icy Veins
			{ itemID = 1013644, desc = "Un'Goro Crater (51, 47)" }, --Ignite
			{ itemID = 1013618, desc = "Blackrock Spire (56, 49)" }, --Impact
			{ itemID = 1013620, desc = "Blackrock Depths (58, 64)" }, --Improved Blizzard
			{ itemID = 1013626, desc = "Blackrock Spire (38, 48)" }, --Improved Counterspell
			{ itemID = 1013612, desc = "Burning Steppes (37, 49)" }, --Improved Fire Blast
			{ itemID = 1013614, desc = "Western Plaguelands (50, 40)" }, --Improved Fireball
			{ itemID = 1013738, desc = "The Deadmines (64, 85)" }, --Improved Frostbolt
			{ itemID = 1013648, desc = "Redridge Mountains (31, 76)" }, --Improved Scorch
			{ itemID = 1013956, desc = "Wetlands (64, 48)" }, --Incineration
			{ itemID = 201556, desc = "Western Plaguelands (50, 67)" }, --Kindling
			{ itemID = 1013628, desc = "Searing Gorge (32, 41)" }, --Magic Attunement
			{ itemID = 200067, desc = "Stranglethorn Vale (27, 55)" }, --Mass Invisibility
			{ itemID = 1013856, desc = "Alterac Mountains (19, 74)" }, --Master of Elements
			{ itemID = 200064, desc = "Scarlet Monastery (60, 88)" }, --Meteor
			{ itemID = 1013623, desc = "Eastern Plaguelands (82, 80)" }, --Permafrost
			{ itemID = 201226, desc = "Dire Maul (32, 40)" }, --Power Overwhelming
			{ itemID = 1013860, desc = "Elwynn Forest (44, 67)" }, --Precision
			{ itemID = 200725, desc = "Burning Steppes (54, 54)" }, --Precision Impact
			{ itemID = 201584, desc = "Redridge Mountains (18, 77)" }, --Pyroclastic Surprise
			{ itemID = 200697, desc = "Feralas (69, 48)" }, --Rapid Blinking
			{ itemID = 201290, desc = "Ashenvale (49, 70)" }, --Rapid Shatter
			{ itemID = 200123 }, --Ring of Frost
			{ itemID = 200727, desc = "Ashenvale (46, 71)" }, --Rune of Power
			{ itemID = 201187, desc = "Burning Steppes (25, 59)" }, --Scorched Ground
			{ itemID = 1013653, desc = "Scholomance (41, 62)" }, --Shatter
			{ itemID = 1013619, desc = "Searing Gorge (28, 43)" }, --Spell Impact
			{ itemID = 1013912 }, --Student of the Mind
			{ itemID = 1013965, desc = "Wetlands (61, 59)" }, --Torment the Weak
			{ itemID = 200372, desc = "Western Plaguelands (58, 81)" }, --Touch of the Magi
			{ itemID = 200916, desc = "Ashenvale (81, 50)" }, --Trisolaris
			{ itemID = 200585, desc = "Alterac Mountains (43, 41)" }, --Wacky Wizardry
			{ itemID = 203025, desc = "Winterspring (58, 31)" }, --Winter's Blaze
			{ itemID = 1013615, desc = "Stranglethorn Vale (31, 54)" }, --World in Flames
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554207 }, --Glyph of Arcane Blast
			{ itemID = 554100, desc = "Stranglethorn Vale (33, 88)" }, --Glyph of Arcane Explosion
			{ itemID = 554101, desc = "Western Plaguelands (41, 52)" }, --Glyph of Arcane Missiles
			{ itemID = 554103, desc = "Felwood (39, 61)" }, --Glyph of Blink
			{ itemID = 554221, desc = "Dire Maul (42, 46)" }, --Glyph of Deep Freeze
			{ itemID = 554275, desc = "Stratholme (47, 23)" }, --Glyph of Eternal Water
			{ itemID = 554116, desc = "Elwynn Forest (44, 67)" }, --Glyph of Evocation
			{ itemID = 554107, desc = "Blackrock Depths (58, 62)" }, --Glyph of Fire Blast
			{ itemID = 554106, desc = "Western Plaguelands (45, 45)" }, --Glyph of Fireball
			{ itemID = 554114, desc = "Western Plaguelands (55, 23)" }, --Glyph of Frost Nova
			{ itemID = 554108, desc = "Scarlet Monastery (52, 65)" }, --Glyph of Frostbolt
			{ itemID = 554120, desc = "Arathi Highlands (26, 65)" }, --Glyph of Ice Armor
			{ itemID = 554225, desc = "The Barrens (62, 39)" }, --Glyph of Ice Barrier
			{ itemID = 554110, desc = "Westfall (34, 83)" }, --Glyph of Ice Block
			{ itemID = 554222 }, --Glyph of Living Bomb
			{ itemID = 554118, desc = "Uldaman (64, 42)" }, --Glyph of Molten Armor
			{ itemID = 554113, desc = "Alterac Mountains (56, 66)" }, --Glyph of Polymorph
			{ itemID = 554109, desc = "Elwynn Forest (44, 67)" }, --Glyph of Scorch
			{ itemID = 554111, desc = "Stratholme (26, 33)" }, --Glyph of Water Elemental
		},
	},
	["MysticEnchantsPaladin"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 201051, desc = "The Hinterlands (27, 49)" }, --A New Dawn
			{ itemID = 1013821, desc = "Arathi Highlands (28, 64)" }, --Anticipation
			{ itemID = 200157 }, --Aura Mastery
			{ itemID = 1013822, desc = "Stratholme (11, 56)" }, --Benediction
			{ itemID = 200975, desc = "Eastern Plaguelands (59, 55)" }, --Blessed Hammer
			{ itemID = 1013953 }, --Blessed Hands
			{ itemID = 200593, desc = "Stratholme (16, 55)" }, --Blessing of the Divines
			{ itemID = 200084, desc = "Tanaris (47, 54)" }, --Blinding Light
			{ itemID = 200607, desc = "Western Plaguelands (43, 15)" }, --Branding Zeal
			{ itemID = 201277, desc = "Loch Modan (35, 48)" }, --Consecrated Weapon
			{ itemID = 200961, desc = "Stratholme (26, 44)" }, --Consecrated Zeal
			{ itemID = 1013823 }, --Conviction
			{ itemID = 200623, desc = "Eastern Plaguelands (36, 23)" }, --Crimson Defense
			{ itemID = 1013602, desc = "Westfall (28, 43)" }, --Crusader of the Light
			{ itemID = 201537, desc = "Arathi Highlands (21, 61)" }, --Crusader's Judgement
			{ itemID = 1013820, desc = "Scarlet Monastery (79, 20)" }, --Deflection
			{ itemID = 1013833, desc = "Tirisfal Glades (60, 55)" }, --Divine Intellect
			{ itemID = 1013609, desc = "Deadwind Pass (41, 78)" }, --Divine Order
			{ itemID = 201569, desc = "Redridge Mountains (21, 52)" }, --Divine Reprieve
			{ itemID = 1013601, desc = "Eastern Plaguelands (75, 79)" }, --Divine Resurgence
			{ itemID = 1013834, desc = "Elwynn Forest (41, 66)" }, --Divine Strength
			{ itemID = 1013981, desc = "Tirisfal Glades (60, 55)" }, --Divinity
			{ itemID = 200116, desc = "Deathknell (53, 59)" }, --Execution Sentence
			{ itemID = 1013847 }, --Eye for an Eye
			{ itemID = 200110, desc = "Western Plaguelands (45, 86)" }, --Gift of Light
			{ itemID = 201439, desc = "The Barrens (63, 38)" }, --Glimmer of Light
			{ itemID = 201240, desc = "Eastern Plaguelands (42, 28)" }, --Guardian of Ancient Kings
			{ itemID = 200410, desc = "Duskwood (74, 45)" }, --Hammerstorm
			{ itemID = 1013830, desc = "Tirisfal Glades (83, 30)" }, --Healing Light
			{ itemID = 1013836, desc = "Eastern Plaguelands (75, 76)" }, --Heart of the Crusader
			{ itemID = 1013895, desc = "Duskwood (13, 29)" }, --Holy Mastery
			{ itemID = 201560, desc = "Durotar (64, 80)" }, --Holy Templar
			{ itemID = 200075, desc = "The Barrens (63, 38)" }, --Holy Templar: Light of Dawn
			{ itemID = 1013828, desc = "Blackrock Depths (38, 77)" }, --Illumination
			{ itemID = 1013819 }, --Improved Blessing of Might
			{ itemID = 1013824, desc = "Western Plaguelands (47, 33)" }, --Improved Devotion Aura
			{ itemID = 1013838, desc = "Stratholme (10, 53)" }, --Improved Hammer of Justice
			{ itemID = 1013846, desc = "Eastern Plaguelands (75, 78)" }, --Improved Judgements
			{ itemID = 1013829, desc = "Eastern Plaguelands (80, 76)" }, --Improved Lay on Hands
			{ itemID = 1013837 }, --Improved Righteous Fury
			{ itemID = 201164, desc = "Elwynn Forest (52, 68)" }, --Light of the Guardian
			{ itemID = 201159, desc = "Silithus (36, 54)" }, --Light's Hammer
			{ itemID = 201578, desc = "The Barrens (52, 23)" }, --Long Arm of the Law
			{ itemID = 201436, desc = "Dun Morogh (58, 45)" }, --One With The Light
			{ itemID = 201132, desc = "Tirisfal Glades (60, 52)" }, --Pious Strikes
			{ itemID = 1013894, desc = "Maraudon (33, 50)" }, --Protection Mastery
			{ itemID = 1013849, desc = "Uldaman (27, 34)" }, --Pursuit of Justice
			{ itemID = 1013896, desc = "Zul'Gurub (49, 40)" }, --Retribution Mastery
			{ itemID = 201540, desc = "Arathi Highlands (21, 63)" }, --Righteous Verdict
			{ itemID = 201437, desc = "Valley of Trials (50, 91)" }, --Sacred Light
			{ itemID = 1013902, desc = "Eastern Plaguelands (81, 72)" }, --Sanctity of Battle
			{ itemID = 200156, desc = "Elwynn Forest (41, 66)" }, --Seal of Command
			{ itemID = 1013835, desc = "Wetlands (54, 54)" }, --Seals of the Pure
			{ itemID = 201393, desc = "Stonetalon Mountains (59, 67)" }, --Spark of Hope
			{ itemID = 1013827, desc = "Scarlet Monastery (75, 29)" }, --Spiritual Focus
			{ itemID = 1013950, desc = "Stratholme (12, 49)" }, --Stoicism
			{ itemID = 201202, desc = "Winterspring (57, 56)" }, --Swift Avenger
			{ itemID = 200726, desc = "Eastern Plaguelands (78, 81)" }, --Swift Execution
			{ itemID = 201012, desc = "Gol'Bolar Quarry (41, 65)" }, --Swift Favor
			{ itemID = 201371, desc = "The Hinterlands (51, 35)" }, --Sword of Vengeance
			{ itemID = 201438, desc = "Stonetalon Mountains (41, 52)" }, --Synergistic Light
			{ itemID = 201009, desc = "Duskwood (74, 45)" }, --Twist of Faith
			{ itemID = 1013845, desc = "Elwynn Forest (41, 66)" }, --Unyielding Faith
			{ itemID = 1013848 }, --Vindication
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554035, desc = "Feralas (69, 41)" }, --Glyph of Avenging Wrath
			{ itemID = 554226, desc = "Tirisfal Glades (60, 55)" }, --Glyph of Beacon of Light
			{ itemID = 554027, desc = "Mulgore (47, 61)" }, --Glyph of Consecration
			{ itemID = 554026, desc = "Eastern Plaguelands (75, 77)" }, --Glyph of Crusader Strike
			{ itemID = 554230 }, --Glyph of Divine Plea
			{ itemID = 554228 }, --Glyph of Divine Storm
			{ itemID = 554036 }, --Glyph of Divinity
			{ itemID = 554031, desc = "Elwynn Forest (41, 66)" }, --Glyph of Exorcism
			{ itemID = 554022, desc = "Hillsbrad Foothills (20, 76)" }, --Glyph of Hammer of Justice
			{ itemID = 554227 }, --Glyph of Hammer of the Righteous
			{ itemID = 554034, desc = "Blackrock Depths (23, 55)" }, --Glyph of Holy Light
			{ itemID = 554123, desc = "Dire Maul (35, 83)" }, --Glyph of Holy Wrath
			{ itemID = 554021, desc = "Western Plaguelands (44, 13)" }, --Glyph of Judgement
			{ itemID = 554232 }, --Glyph of Salvation
			{ itemID = 554024, desc = "Tirisfal Glades (60, 55)" }, --Glyph of Seal of Command
			{ itemID = 554121 }, --Glyph of Seal of Righteousness
			{ itemID = 554037, desc = "Tirisfal Glades (60, 55)" }, --Glyph of Seal of Wisdom
			{ itemID = 554122, desc = "Arathi Highlands (23, 57)" }, --Glyph of Vengeance
		},
	},
	["MysticEnchantsPriest"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 1013867, desc = "Blasted Lands (45, 54)" }, --Absolution
			{ itemID = 200605, desc = "Western Plaguelands (44, 21)" }, --Accelerated Ascension
			{ itemID = 1013906, desc = "Stratholme (12, 49)" }, --Afterkindling
			{ itemID = 200070, desc = "The Hinterlands (38, 65)" }, --Angelic Feather
			{ itemID = 201156, desc = "Hillsbrad Foothills (79, 57)" }, --Armor of Faith
			{ itemID = 200869, desc = "Duskwood (91, 31)" }, --Atonement
			{ itemID = 1013905, desc = "Scarlet Monastery (Entrance) (80, 46)" }, --Blessed Vengeance
			{ itemID = 201288, desc = "Hillsbrad Foothills (29, 40)" }, --Centered
			{ itemID = 200479, desc = "Dustwallow Marsh (30, 48)" }, --Circle of Life
			{ itemID = 201463, desc = "Redridge Mountains (69, 55)" }, --Dark Focus
			{ itemID = 201172, desc = "Desolace (51, 86)" }, --Dark Power Well
			{ itemID = 1013700, desc = "Eastern Plaguelands (78, 74)" }, --Darkness
			{ itemID = 1013879, desc = "Western Plaguelands (43, 20)" }, --Discipline Mastery
			{ itemID = 1013786, desc = "Silverpine Forest (47, 85)" }, --Divine Fury
			{ itemID = 200072, desc = "Scarlet Monastery (Entrance) (19, 93)" }, --Divine Star
			{ itemID = 201514, desc = "Feralas (72, 63)" }, --Endless Void
			{ itemID = 201185, desc = "Stonetalon Mountains (41, 17)" }, --Energizing Prayer
			{ itemID = 201237, desc = "Westfall (58, 54)" }, --Faith Rekindled
			{ itemID = 201264, desc = "Hillsbrad Foothills (14, 83)" }, --Good Fortune
			{ itemID = 1013606, desc = "The Hinterlands (35, 57)" }, --Grateful Prayer
			{ itemID = 200111, desc = "Desolace (30, 10)" }, --Halo
			{ itemID = 1013696, desc = "Scarlet Monastery (24, 50)" }, --Healing Focus
			{ itemID = 201126, desc = "Stranglethorn Vale (45, 10)" }, --Higher Power
			{ itemID = 200606, desc = "Blackrock Depths (50, 59)" }, --Holy Ascension
			{ itemID = 1013878, desc = "Hillsbrad Foothills (30, 43)" }, --Holy Mastery
			{ itemID = 201165, desc = "Searing Gorge (32, 57)" }, --Holy Power Well
			{ itemID = 200590, desc = "Stranglethorn Vale (45, 10)" }, --Holy Radiance
			{ itemID = 1013850, desc = "Northshire Valley (39, 44)" }, --Holy Reach
			{ itemID = 200974, desc = "Scarlet Monastery (48, 43)" }, --Holy Servitude
			{ itemID = 1013695 }, --Holy Specialization
			{ itemID = 200784, desc = "Hillsbrad Foothills (15, 83)" }, --Holy Word: Chastise
			{ itemID = 201249, desc = "Azshara (72, 17)" }, --Impending Doom
			{ itemID = 1013697, desc = "Blackrock Spire (52, 50)" }, --Improved Healing
			{ itemID = 1013687, desc = "Western Plaguelands (52, 84)" }, --Improved Inner Fire
			{ itemID = 1013688, desc = "Searing Gorge (68, 48)" }, --Improved Mana Burn
			{ itemID = 1013702, desc = "Azshara (73, 13)" }, --Improved Mind Blast
			{ itemID = 1013685, desc = "Blackrock Depths (38, 60)" }, --Improved Power Word: Fortitude
			{ itemID = 1013686, desc = "Stratholme (13, 50)" }, --Improved Power Word: Shield
			{ itemID = 1013710, desc = "Zul'Gurub (51, 38)" }, --Improved Psychic Scream
			{ itemID = 1013764, desc = "Stratholme (21, 50)" }, --Improved Renew
			{ itemID = 1013703, desc = "Tirisfal Glades (48, 31)" }, --Improved Shadow Word: Pain
			{ itemID = 1013708, desc = "Scholomance (63, 28)" }, --Improved Spirit Tap
			{ itemID = 1013709, desc = "Blackrock Depths (23, 56)" }, --Inspiration
			{ itemID = 1300143, desc = "Winterspring (68, 74)" }, --Leap of Faith
			{ itemID = 201565, desc = "Dun Morogh (46, 49)" }, --Light and Shadow
			{ itemID = 1013689, desc = "Scarlet Monastery (Entrance) (77, 55)" }, --Martyrdom
			{ itemID = 1013691, desc = "Western Plaguelands (55, 36)" }, --Mental Agility
			{ itemID = 201480, desc = "The Barrens (61, 40)" }, --Pendulum
			{ itemID = 201282, desc = "Tanaris (67, 22)" }, --Power of Generosity
			{ itemID = 201517, desc = "Dustwallow Marsh (34, 70)" }, --Power Word: Barrier
			{ itemID = 200748, desc = "Eastern Plaguelands (76, 52)" }, --Prayer Circle
			{ itemID = 201591, desc = "Redridge Mountains (22, 58)" }, --Promise of Renewal
			{ itemID = 554401, desc = "Eastern Plaguelands (74, 40)" }, --Psychic Influence
			{ itemID = 201580, desc = "Redridge Mountains (52, 76)" }, --Psychic Infusion
			{ itemID = 200143, desc = "Ashenvale (49, 70)" }, --Purgation by Light
			{ itemID = 200911, desc = "Eastern Plaguelands (81, 78)" }, --Purity of Light
			{ itemID = 200592, desc = "Alterac Mountains (63, 48)" }, --Renewed Through Absolution
			{ itemID = 1013698, desc = "Scarlet Monastery (83, 83)" }, --Searing Light
			{ itemID = 1013704, desc = "Stratholme (23, 58)" }, --Shadow Affinity
			{ itemID = 1013705, desc = "Blackrock Spire (37, 24)" }, --Shadow Focus
			{ itemID = 1013880, desc = "Wetlands (11, 59)" }, --Shadow Mastery
			{ itemID = 1013765, desc = "Blackrock Depths (47, 94)" }, --Shadow Reach
			{ itemID = 201533, desc = "Silverpine Forest (64, 66)" }, --Shadow Reserves
			{ itemID = 200555, desc = "Tanaris (52, 28)" }, --Shadow Visions
			{ itemID = 201581, desc = "Darkshore (39, 95)" }, --Shattered Renewal
			{ itemID = 1013692, desc = "Stranglethorn Vale (44, 11)" }, --Silent Resolve
			{ itemID = 200153, desc = "Badlands (42, 29)" }, --Soul Restoration
			{ itemID = 200644, desc = "Western Plaguelands (52, 45)" }, --Spirited Penance
			{ itemID = 200776, desc = "Twilight's Run (46, 78)" }, --Twilight Paragon
			{ itemID = 1013948, desc = "Blackrock Spire (56, 45)" }, --Twin Disciplines
			{ itemID = 1013693, desc = "Eastern Plaguelands (65, 30)" }, --Unbreakable Will
			{ itemID = 200078, desc = "Silverpine Forest (50, 41)" }, --Void Eruption
			{ itemID = 200195, desc = "Deadwind Pass (55, 79)" }, --Void Herald: Grasp of Darkness
			{ itemID = 200586, desc = "Desolace (50, 7)" }, --Void Herald: Whispers of the Old Gods
			{ itemID = 200099, desc = "Desolace (55, 80)" }, --Void Shift
			{ itemID = 201100, desc = "Wetlands (34, 49)" }, --Wanding
			{ itemID = 200860, desc = "Eastern Plaguelands (43, 38)" }, --Words of Healing
			{ itemID = 200158, desc = "Arathi Highlands (27, 63)" }, --Wraithweaver: Echoing Shadows
			{ itemID = 201564, desc = "Arathi Highlands (68, 81)" }, --Wraithweaver: Shadow Orbs
			{ itemID = 200886, desc = "Arathi Highlands (32, 34)" }, --Zany Zealot
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554061 }, --Glyph of Circle of Healing
			{ itemID = 554063, desc = "Stonetalon Mountains (37, 15)" }, --Glyph of Dispel Magic
			{ itemID = 554064, desc = "Eastern Plaguelands (74, 39)" }, --Glyph of Fear Ward
			{ itemID = 554065, desc = "Arathi Highlands (23, 61)" }, --Glyph of Flash Heal
			{ itemID = 554069 }, --Glyph of Holy Nova
			{ itemID = 554072, desc = "Northshire Valley (39, 44)" }, --Glyph of Inner Fire
			{ itemID = 554073, desc = "The Temple of Atal'hakkar (74, 58)" }, --Glyph of Mind Flay
			{ itemID = 554235 }, --Glyph of Penance
			{ itemID = 554058, desc = "Elwynn Forest (43, 66)" }, --Glyph of Power Word: Shield
			{ itemID = 554062, desc = "Silithus (26, 37)" }, --Glyph of Psychic Scream
			{ itemID = 554060, desc = "Scarlet Monastery (Entrance) (79, 29)" }, --Glyph of Renew
			{ itemID = 554076, desc = "Deathknell (48, 59)" }, --Glyph of Scourge Imprisonment
			{ itemID = 554075, desc = "Eastern Plaguelands (22, 32)" }, --Glyph of Shadow
			{ itemID = 554067, desc = "Silverpine Forest (58, 70)" }, --Glyph of Shadow Word: Pain
			{ itemID = 554078, desc = "Scarlet Monastery (22, 48)" }, --Glyph of Smite
			{ itemID = 1013904, desc = "Scarlet Monastery (Entrance) (78, 29)" }, --Glyph of Surge of Light
		},
	},
	["MysticEnchantsRogue"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 201385, desc = "Tanaris (73, 47)" }, --Adrenaline Junkie
			{ itemID = 1013977, desc = "Elwynn Forest (79, 46)" }, --Aggression
			{ itemID = 201086, desc = "Alterac Mountains (39, 16)" }, --Assassin's Rush
			{ itemID = 200577, desc = "Searing Gorge (35, 35)" }, --Assuaging Shadows
			{ itemID = 201005, desc = "Tanaris (50, 69)" }, --Blade Vortex
			{ itemID = 201450, desc = "Loch Modan (60, 14)" }, --Bleeding Edge
			{ itemID = 1013943, desc = "Eastern Plaguelands (64, 13)" }, --Blood Spatter
			{ itemID = 201048, desc = "Feralas (55, 58)" }, --Blood-Soaked Mutilation
			{ itemID = 201441, desc = "Eastern Plaguelands (55, 69)" }, --Bloodshed
			{ itemID = 1013670, desc = "Stranglethorn Vale (25, 69)" }, --Camouflage
			{ itemID = 1013659 }, --Close Quarters Combat
			{ itemID = 1013882, desc = "Westfall (56, 53)" }, --Combat Mastery
			{ itemID = 201447, desc = "The Hinterlands (67, 75)" }, --Combat Proficiency
			{ itemID = 200114, desc = "Alterac Mountains (62, 44)" }, --Crimson Tempest
			{ itemID = 1013662, desc = "Blackrock Depths (42, 83)" }, --Deflection
			{ itemID = 1013675, desc = "Shadowglen (49, 53)" }, --Dirty Tricks
			{ itemID = 200102, desc = "Stranglethorn Vale (34, 86)" }, --Dispatch
			{ itemID = 201304, desc = "Alterac Mountains (59, 32)" }, --Doppelganger
			{ itemID = 1013661, desc = "Scarlet Monastery (83, 32)" }, --Dual Wield Specialization
			{ itemID = 1013666, desc = "Maraudon (50, 71)" }, --Endurance
			{ itemID = 201542, desc = "Elwynn Forest (81, 67)" }, --Energy Surge
			{ itemID = 201092, desc = "Westfall (71, 74)" }, --Envenomed
			{ itemID = 201596, desc = "Tanaris (65, 40)" }, --Fatal Counter
			{ itemID = 200556, desc = "Arathi Highlands (38, 21)" }, --Festering Wound
			{ itemID = 201113, desc = "Burning Steppes (65, 40)" }, --From the Shadows
			{ itemID = 200941 }, --Hastened Feint
			{ itemID = 201329, desc = "Loch Modan (35, 17)" }, --Hazardous Escape
			{ itemID = 1013674 }, --Improved Ambush
			{ itemID = 1013681 }, --Improved Eviscerate
			{ itemID = 1013658, desc = "Wetlands (16, 36)" }, --Improved Gouge
			{ itemID = 1013676, desc = "Stratholme (66, 55)" }, --Improved Poisons
			{ itemID = 1013663, desc = "Arathi Highlands (27, 63)" }, --Improved Sinister Strike
			{ itemID = 1013669, desc = "Shadowglen (49, 53)" }, --Initiative
			{ itemID = 200397, desc = "Redridge Mountains (26, 47)" }, --Kingsbane
			{ itemID = 1013677, desc = "Blackrock Spire (55, 36)" }, --Lethality
			{ itemID = 1013657, desc = "Stranglethorn Vale (27, 77)" }, --Lightning Reflexes
			{ itemID = 200955, desc = "Un'Goro Crater (23, 42)" }, --Massacre
			{ itemID = 1013668 }, --Master of Deception
			{ itemID = 201320, desc = "Arathi Highlands (27, 62)" }, --Methodical Approach
			{ itemID = 201567, desc = "The Barrens (55, 6)" }, --Murder Rush
			{ itemID = 200557, desc = "Sunwell Plateau (58, 31)" }, --Natural Energy
			{ itemID = 201539, desc = "Northshire Valley (33, 53)" }, --No Remorse
			{ itemID = 1013673, desc = "Alterac Mountains (48, 82)" }, --Opportunity
			{ itemID = 201602, desc = "Hillsbrad Foothills (67, 47)" }, --Phantom Stab
			{ itemID = 200310, desc = "Hillsbrad Foothills (15, 54)" }, --Poison Bomb
			{ itemID = 1013660 }, --Precision
			{ itemID = 1013664, desc = "Burning Steppes (62, 38)" }, --Puncturing Wounds
			{ itemID = 1013972 }, --Relentless Strikes
			{ itemID = 1013679, desc = "Alterac Mountains (63, 45)" }, --Remorseless Attacks
			{ itemID = 201381, desc = "Silverpine Forest (65, 25)" }, --Repartee
			{ itemID = 200144 }, --Riposte
			{ itemID = 201283, desc = "Feralas (55, 58)" }, --Rush of Blood
			{ itemID = 1013680, desc = "The Stockade (32, 34)" }, --Ruthlessness
			{ itemID = 1013684, desc = "The Stockade (49, 36)" }, --Serrated Blades
			{ itemID = 201118, desc = "The Hinterlands (66, 75)" }, --Shadow Blades
			{ itemID = 200579, desc = "Tanaris (52, 90)" }, --Shadow of Death
			{ itemID = 201031, desc = "Alterac Mountains (59, 67)" }, --Shattering Execution
			{ itemID = 201448, desc = "Westfall (52, 22)" }, --Sinister Finisher
			{ itemID = 201223, desc = "Loch Modan (34, 48)" }, --Sinister Flurry
			{ itemID = 1013883, desc = "Desolace (74, 25)" }, --Subtlety Mastery
			{ itemID = 201361, desc = "Burning Steppes (64, 49)" }, --Veiled Wire
			{ itemID = 200671, desc = "Un'Goro Crater (67, 52)" }, --Venomous Edge
			{ itemID = 1013735, desc = "Arathi Highlands (55, 38)" }, --Vile Poisons
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554139 }, --Glyph of Ambush
			{ itemID = 554126, desc = "Gold Coast Quarry (50, 22)" }, --Glyph of Backstab
			{ itemID = 554143, desc = "Dire Maul (31, 69)" }, --Glyph of Crippling Poison
			{ itemID = 554125, desc = "Maraudon (48, 67)" }, --Glyph of Evasion
			{ itemID = 554128, desc = "Elwynn Forest (44, 67)" }, --Glyph of Eviscerate
			{ itemID = 554242 }, --Glyph of Fan of Knives
			{ itemID = 554138 }, --Glyph of Garrote
			{ itemID = 554140, desc = "Shadowglen (49, 53)" }, --Glyph of Ghostly Strike
			{ itemID = 554135, desc = "Burning Steppes (63, 40)" }, --Glyph of Gouge
			{ itemID = 554133, desc = "Stranglethorn Vale (27, 77)" }, --Glyph of Hemorrhage
			{ itemID = 554244, desc = "The Stockade (68, 38)" }, --Glyph of Mutilate
			{ itemID = 554142, desc = "Blackrock Depths (56, 67)" }, --Glyph of Preparation
			{ itemID = 554127, desc = "Eastern Plaguelands (80, 35)" }, --Glyph of Rupture
			{ itemID = 554124, desc = "Stranglethorn Vale (27, 77)" }, --Glyph of Sap
			{ itemID = 554144, desc = "Dun Morogh (35, 52)" }, --Glyph of Sinister Strike
			{ itemID = 554136, desc = "Teldrassil (58, 59)" }, --Glyph of Slice and Dice
			{ itemID = 554137 }, --Glyph of Sprint
			{ itemID = 554131 }, --Glyph of Vigor
		},
	},
	["MysticEnchantsShaman"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 200118, desc = "Blasted Lands (58, 47)" }, --Air Ascendance
			{ itemID = 1013725, desc = "The Hinterlands (66, 44)" }, --Ancestral Healing
			{ itemID = 1013766 }, --Ancestral Knowledge
			{ itemID = 1013726, desc = "Westfall (35, 37)" }, --Anticipation
			{ itemID = 202566, desc = "Stranglethorn Vale (30, 20)" }, --Ascending Flames
			{ itemID = 200109, desc = "Arathi Highlands (36, 58)" }, --Astral Plane
			{ itemID = 200559, desc = "Duskwood (76, 47)" }, --Booming Thunder
			{ itemID = 1013715, desc = "Blackrock Spire (39, 49)" }, --Call of Flame
			{ itemID = 201493, desc = "Dustwallow Marsh (53, 68)" }, --Capacitor Totem
			{ itemID = 201413, desc = "Burning Steppes (53, 42)" }, --Cataclysmic Sundering
			{ itemID = 201311, desc = "Loch Modan (35, 93)" }, --Charged Tides
			{ itemID = 200062, desc = "Sinister Lair (53, 69)" }, --Cloudburst Totem
			{ itemID = 1013711, desc = "Eastern Plaguelands (34, 85)" }, --Concussion
			{ itemID = 1013712, desc = "Stranglethorn Vale (44, 20)" }, --Convection
			{ itemID = 201541, desc = "Elwynn Forest (81, 57)" }, --Crackling Flames
			{ itemID = 201831, desc = "Wailing Caverns (46, 59)" }, --Defense of Thundarian
			{ itemID = 200901, desc = "Dustwallow Marsh (59, 10)" }, --Dynamic Charge
			{ itemID = 1013714, desc = "Winterspring (41, 43)" }, --Earth's Grasp
			{ itemID = 201473, desc = "Ashenvale (31, 45)" }, --Earthen Grace
			{ itemID = 200130, desc = "Arathi Highlands (63, 34)" }, --Earthen Guardian Mastery
			{ itemID = 200097, desc = "Darkshore (55, 35)" }, --Earthen Spike
			{ itemID = 201492, desc = "Badlands (16, 38)" }, --Earthquake
			{ itemID = 200889, desc = "Un'Goro Crater (45, 6)" }, --Eccentric Elementalist
			{ itemID = 201604, desc = "Arathi Highlands (20, 68)" }, --Electric Surge
			{ itemID = 201488, desc = "Arathi Highlands (22, 81)" }, --Elemental Blast
			{ itemID = 1013858, desc = "Camp Narache (30, 26)" }, --Elemental Devastation
			{ itemID = 201477, desc = "Arathi Highlands (35, 59)" }, --Elemental Equilibrium
			{ itemID = 1013716, desc = "The Deadmines (55, 37)" }, --Elemental Focus
			{ itemID = 1013975, desc = "Scholomance (31, 38)" }, --Elemental Fury
			{ itemID = 201606, desc = "Loch Modan (70, 62)" }, --Elemental Harmony
			{ itemID = 1013888, desc = "Azshara (44, 27)" }, --Elemental Mastery
			{ itemID = 1013854 }, --Elemental Warding
			{ itemID = 1013857, desc = "The Deadmines (59, 59)" }, --Elemental Weapons
			{ itemID = 1013890, desc = "Tanaris (31, 78)" }, --Enhancement Mastery
			{ itemID = 1013855, desc = "Stranglethorn Vale (48, 43)" }, --Eye of the Storm
			{ itemID = 200061, desc = "Badlands (74, 66)" }, --Flame Ascendance
			{ itemID = 201486, desc = "Searing Gorge (73, 79)" }, --Forked Lightning
			{ itemID = 200935, desc = "Stranglethorn Vale (25, 24)" }, --Frugal Disposition
			{ itemID = 201027, desc = "Desolace (31, 81)" }, --Fury of the Wind
			{ itemID = 1013724, desc = "Redridge Mountains (26, 22)" }, --Healing Focus
			{ itemID = 1013859, desc = "Arathi Highlands (17, 69)" }, --Healing Grace
			{ itemID = 200124, desc = "Desolace (33, 22)" }, --Healing Rain
			{ itemID = 201513, desc = "Ashenvale (40, 33)" }, --Healing Tide
			{ itemID = 201475, desc = "Silverpine Forest (43, 41)" }, --Hydromancer: Water Bolt
			{ itemID = 201474, desc = "Ashenvale (11, 27)" }, --Hydromancer: Water Nova
			{ itemID = 1013736, desc = "Gnomeregan (51, 84)" }, --Improved Fire Nova
			{ itemID = 1013728 }, --Improved Ghost Wolf
			{ itemID = 1013723, desc = "Searing Gorge (24, 37)" }, --Improved Healing Wave
			{ itemID = 1013945, desc = "Arathi Highlands (21, 85)" }, --Improved Shields
			{ itemID = 1013717, desc = "Uldaman (54, 74)" }, --Improved Water Shield
			{ itemID = 201603, desc = "Hillsbrad Foothills (51, 59)" }, --Lava Ignition
			{ itemID = 200174, desc = "Burning Steppes (30, 47)" }, --Lava Sweep
			{ itemID = 201415, desc = "Winterspring (51, 26)" }, --Leader of the Elements
			{ itemID = 200922, desc = "Winterspring (66, 17)" }, --Lightning Fangs
			{ itemID = 200851, desc = "Blackfathom Deeps (58, 71)" }, --Low Tide
			{ itemID = 201481, desc = "Tanaris (70, 40)" }, --Mastery of Lightning
			{ itemID = 200565, desc = "Stranglethorn Vale (15, 16)" }, --Mending Tide
			{ itemID = 201485, desc = "Searing Gorge (25, 26)" }, --Molten Outburst
			{ itemID = 200999, desc = "Badlands (14, 76)" }, --Nature's Flow
			{ itemID = 201489, desc = "Swamp of Sorrows (66, 30)" }, --Pack Alpha
			{ itemID = 201314, desc = "Dustwallow Marsh (56, 63)" }, --Primal Tide
			{ itemID = 200807, desc = "Blackrock Depths (43, 75)" }, --Primordial Aftershocks
			{ itemID = 1013889, desc = "Northshire Valley (45, 47)" }, --Restoration Mastery
			{ itemID = 1013713, desc = "Lower Blackrock Mountain (37, 25)" }, --Reverberation
			{ itemID = 1013911, desc = "The Deadmines (42, 35)" }, --Shamanistic Focus
			{ itemID = 201516, desc = "Loch Modan (70, 61)" }, --Shock Tactics
			{ itemID = 202576, desc = "Stranglethorn Vale (14, 14)" }, --Spirit Link Totem
			{ itemID = 200854, desc = "Azshara (72, 7)" }, --Spreading Tides
			{ itemID = 200652, desc = "Arathi Highlands (51, 49)" }, --Stormborn
			{ itemID = 200141, desc = "Azshara (62, 65)" }, --Stormbound Instinct
			{ itemID = 1013730 }, --Thundering Strikes
			{ itemID = 1013720, desc = "Redridge Mountains (82, 60)" }, --Tidal Focus
			{ itemID = 1013721, desc = "Dun Morogh (41, 45)" }, --Tidal Mastery
			{ itemID = 201571, desc = "Arathi Highlands (32, 45)" }, --Tides of Restoration
			{ itemID = 201482, desc = "Arathi Highlands (20, 68)" }, --Totem Master: Fire
			{ itemID = 1013722, desc = "Stranglethorn Vale (49, 8)" }, --Totemic Focus
			{ itemID = 201186, desc = "Stranglethorn Vale (15, 28)" }, --Transcendental Embrace
			{ itemID = 200924, desc = "Tanaris (50, 78)" }, --Ungrounded
			{ itemID = 200925, desc = "Silithus (20, 18)" }, --Wind Lash
			{ itemID = 200090, desc = "Arathi Highlands (21, 81)" }, --Windwalk Totem
			{ itemID = 201394, desc = "Tanaris (30, 78)" }, --Zephyr
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554039, desc = "Silverpine Forest (45, 74)" }, --Glyph of Chain Heal
			{ itemID = 554051, desc = "Stranglethorn Vale (51, 16)" }, --Glyph of Chain Lightning
			{ itemID = 554249, desc = "Durotar (54, 43)" }, --Glyph of Earth Shield
			{ itemID = 200127, desc = "Mulgore (48, 59)" }, --Glyph of Earthen Guardian
			{ itemID = 554247, desc = "Camp Narache (30, 26)" }, --Glyph of Feral Spirit
			{ itemID = 554057, desc = "Mulgore (48, 59)" }, --Glyph of Fire Elemental Totem
			{ itemID = 554052, desc = "Blackrock Spire (50, 46)" }, --Glyph of Fire Nova
			{ itemID = 554049, desc = "Western Plaguelands (48, 70)" }, --Glyph of Flame Shock
			{ itemID = 554053, desc = "Northshire Valley (35, 56)" }, --Glyph of Flametongue Weapon
			{ itemID = 554045, desc = "Blackrock Depths (37, 73)" }, --Glyph of Frost Shock
			{ itemID = 554042, desc = "Uldaman (62, 67)" }, --Glyph of Healing Wave
			{ itemID = 554251, desc = "The Hinterlands (68, 71)" }, --Glyph of Hex
			{ itemID = 554056, desc = "Lower Blackrock Mountain (38, 19)" }, --Glyph of Lava
			{ itemID = 554040, desc = "Arathi Highlands (18, 69)" }, --Glyph of Lesser Healing Wave
			{ itemID = 554055, desc = "Redridge Mountains (27, 28)" }, --Glyph of Lightning Bolt
			{ itemID = 554050, desc = "Northshire Valley (35, 55)" }, --Glyph of Lightning Shield
			{ itemID = 554248 }, --Glyph of Riptide
			{ itemID = 200149, desc = "Northshire Valley (35, 56)" }, --Glyph of Shamanistic Strikes
			{ itemID = 554252, desc = "Dun Morogh (46, 53)" }, --Glyph of Stoneclaw Totem
			{ itemID = 554048, desc = "Dustwallow Marsh (59, 10)" }, --Glyph of Stormstrike
			{ itemID = 554246 }, --Glyph of Thunder
			{ itemID = 554250, desc = "Northshire Valley (35, 56)" }, --Glyph of Totem of Wrath
			{ itemID = 554047, desc = "Durotar (54, 43)" }, --Glyph of Windfury Weapon
		},
	},
	["MysticEnchantsWarlock"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 1013877, desc = "Desolace (76, 27)" }, --Affliction Mastery
			{ itemID = 1013776, desc = "Arathi Highlands (48, 88)" }, --Aftermath
			{ itemID = 1013985, desc = "Felwood (38, 47)" }, --Agent of Chaos
			{ itemID = 201454, desc = "Blasted Lands (66, 32)" }, --Agonizing Coil
			{ itemID = 1013769, desc = "Scarlet Monastery (64, 56)" }, --Bane
			{ itemID = 200712, desc = "Durotar (52, 42)" }, --Bane of Havoc
			{ itemID = 200093, desc = "Stranglethorn Vale (52, 29)" }, --Blood Horror
			{ itemID = 200112, desc = "Searing Gorge (61, 57)" }, --Burning Rush
			{ itemID = 1013767, desc = "Scarlet Monastery (65, 55)" }, --Cataclysm
			{ itemID = 201459, desc = "Zul'Gurub (58, 39)" }, --Cataclysmic Burst
			{ itemID = 201136, desc = "Felwood (42, 39)" }, --Chaos Manifesting
			{ itemID = 200804, desc = "Stranglethorn Vale (41, 59)" }, --Cursed Shadows
			{ itemID = 201453, desc = "The Barrens (41, 17)" }, --Curseweaver
			{ itemID = 201576, desc = "Loch Modan (59, 14)" }, --Dark Harvest
			{ itemID = 201419, desc = "Blasted Lands (46, 23)" }, --Decisive Decimation
			{ itemID = 1013791, desc = "Scholomance (32, 67)" }, --Demonic Brutality
			{ itemID = 200570, desc = "Winterspring (60, 84)" }, --Demonic Influence
			{ itemID = 200800, desc = "Stranglethorn Vale (29, 82)" }, --Demonic Persistence
			{ itemID = 200571, desc = "Feralas (58, 45)" }, --Demonic Reoccurence
			{ itemID = 200763, desc = "Scholomance (73, 39)" }, --Demonic Siphon
			{ itemID = 200699, desc = "Blasted Lands (34, 50)" }, --Demonic Whirl
			{ itemID = 1013876, desc = "Desolace (81, 77)" }, --Demonology Mastery
			{ itemID = 1013875, desc = "Ashenvale (79, 86)" }, --Destruction Mastery
			{ itemID = 1013773, desc = "Scarlet Monastery (Entrance) (57, 42)" }, --Destructive Reach
			{ itemID = 201455, desc = "Felwood (46, 83)" }, --Doomcaller's Wrath
			{ itemID = 200952, desc = "Eastern Plaguelands (35, 31)" }, --Dusk Till Dawn
			{ itemID = 1013866, desc = "Ashenvale (78, 43)" }, --Empowered Corruption
			{ itemID = 200568, desc = "Blasted Lands (46, 16)" }, --Endless Agony
			{ itemID = 200131, desc = "Desolace (48, 86)" }, --Enslave Demon
			{ itemID = 1013768, desc = "Western Plaguelands (46, 52)" }, --Fel Concentration
			{ itemID = 200996, desc = "Swamp of Sorrows (64, 23)" }, --Fel Damnation
			{ itemID = 200951, desc = "Tanaris (39, 56)" }, --Fire Attunement
			{ itemID = 1013782, desc = "Zul'Gurub (59, 74)" }, --Grim Reach
			{ itemID = 200104, desc = "Blasted Lands (54, 56)" }, --Hand of Gul'dan
			{ itemID = 200857, desc = "Burning Steppes (21, 48)" }, --Heating Up!
			{ itemID = 200801, desc = "Desolace (53, 80)" }, --Heretic of Gul'dan
			{ itemID = 1013772, desc = "The Temple of Atal'hakkar (74, 60)" }, --Improved Corruption
			{ itemID = 1013796, desc = "Ragefire Chasm (32, 75)" }, --Improved Curse of Agony
			{ itemID = 1013780, desc = "Stranglethorn Vale (28, 83)" }, --Improved Curse of Weakness
			{ itemID = 1013954, desc = "Blackrock Spire (57, 43)" }, --Improved Fear
			{ itemID = 1013770, desc = "Duskwood (16, 37)" }, --Improved Shadow Bolt
			{ itemID = 201451, desc = "Badlands (52, 32)" }, --Inner Flame
			{ itemID = 1013778, desc = "Duskwood (65, 66)" }, --Intensity
			{ itemID = 1013792, desc = "Wetlands (63, 30)" }, --Master Summoner
			{ itemID = 201456, desc = "Ashenvale (79, 85)" }, --Nether Portal
			{ itemID = 1013775, desc = "Duskwood (16, 37)" }, --Nightfall
			{ itemID = 1013974, desc = "Swamp of Sorrows (60, 21)" }, --Ruin
			{ itemID = 201529, desc = "Arathi Basin (66, 69)" }, --Searing Flames
			{ itemID = 200621, desc = "Felwood (36, 45)" }, --Shadow Crash
			{ itemID = 201570, desc = "Westfall (62, 77)" }, --Shadow Funnel
			{ itemID = 200150 }, --Shadowburn
			{ itemID = 201460, desc = "Swamp of Sorrows (58, 25)" }, --Soul Erosion
			{ itemID = 200049, desc = "Desolace (50, 77)" }, --Soul Harvest
			{ itemID = 200152, desc = "Arathi Highlands (27, 62)" }, --Soul Link
			{ itemID = 1013771, desc = "Stratholme (66, 25)" }, --Soul Siphon
			{ itemID = 200105, desc = "Azshara (14, 74)" }, --Soul Swap
			{ itemID = 201573, desc = "Silverpine Forest (68, 26)" }, --Sudden Aftermath
			{ itemID = 1013779, desc = "Arathi Highlands (69, 81)" }, --Suppression
			{ itemID = 201544, desc = "Ashenvale (25, 60)" }, --Twilight Reaper
			{ itemID = 200091, desc = "Eastern Plaguelands (77, 35)" }, --Unending Resolve
			{ itemID = 1013795, desc = "Dun Morogh (47, 54)" }, --Unholy Power
			{ itemID = 201364, desc = "Felwood (40, 56)" }, --Unstable Void
			{ itemID = 200572, desc = "Felwood (42, 35)" }, --Wild Felfire
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554089, desc = "Blackrock Depths (61, 68)" }, --Glyph of Conflagrate
			{ itemID = 554081, desc = "Blackrock Spire (52, 47)" }, --Glyph of Corruption
			{ itemID = 554092, desc = "Blackrock Depths (90, 10)" }, --Glyph of Curse of Agony
			{ itemID = 554094, desc = "Eastern Plaguelands (74, 40)" }, --Glyph of Fear
			{ itemID = 554084, desc = "Burning Steppes (34, 54)" }, --Glyph of Immolate
			{ itemID = 554097, desc = "Durotar (50, 42)" }, --Glyph of Imp
			{ itemID = 554093, desc = "Elwynn Forest (45, 67)" }, --Glyph of Incinerate
			{ itemID = 554259, desc = "The Barrens (62, 39)" }, --Glyph of Life Tap
			{ itemID = 554276, desc = "Blackfathom Deeps (39, 34)" }, --Glyph of Quick Decay
			{ itemID = 554091, desc = "Hillsbrad Foothills (81, 47)" }, --Glyph of Shadow Bolt
			{ itemID = 554258 }, --Glyph of Soul Link
			{ itemID = 554096, desc = "Elwynn Forest (43, 67)" }, --Glyph of Voidwalker
		},
	},
	["MysticEnchantsWarrior"] = {
		{
			{ icon = "INV_Box_01", name = "Mystic Scrolls" },
			{ itemID = 200626, desc = "Ashenvale (74, 61)" }, --Ambidextrous
			{ itemID = 1013636, desc = "Stranglethorn Vale (34, 16)" }, --Anticipation
			{ itemID = 1013976, desc = "Swamp of Sorrows (45, 57)" }, --Armored to the Teeth
			{ itemID = 200048, desc = "Alterac Mountains (47, 48)" }, --Avatar
			{ itemID = 201217, desc = "Blasted Lands (48, 42)" }, --Battering Ram
			{ itemID = 1013605, desc = "Durotar (46, 50)" }, --Blood and Thunder
			{ itemID = 1013733, desc = "Uldaman (61, 93)" }, --Blood Craze
			{ itemID = 201230, desc = "The Hinterlands (64, 83)" }, --Bloodthirsty
			{ itemID = 1013642, desc = "Scarlet Monastery (52, 40)" }, --Booming Voice
			{ itemID = 201579, desc = "Thousand Needles (44, 38)" }, --Brutal Execution
			{ itemID = 200240, desc = "Stranglethorn Vale (37, 15)" }, --Bulwark
			{ itemID = 1300145, desc = "Searing Gorge (56, 49)" }, --Colossus Smash
			{ itemID = 1013646, desc = "Swamp of Sorrows (45, 57)" }, --Commanding Presence
			{ itemID = 201388, desc = "Duskwood (16, 38)" }, --Counterpoise
			{ itemID = 201225, desc = "Darkshore (37, 44)" }, --Crackling Thunder
			{ itemID = 1013645, desc = "Swamp of Sorrows (45, 57)" }, --Cruelty
			{ itemID = 1013647, desc = "Swamp of Sorrows (45, 57)" }, --Deep Wounds
			{ itemID = 1013732, desc = "Redridge Mountains (69, 56)" }, --Deflection
			{ itemID = 201142, desc = "The Hinterlands (61, 67)" }, --Desperation
			{ itemID = 201432, desc = "Silithus (41, 89)" }, --Devastating Blademaster
			{ itemID = 200179, desc = "Wetlands (83, 50)" }, --Dragon Roar
			{ itemID = 200507, desc = "The Barrens (65, 40)" }, --Dragon Warrior
			{ itemID = 1013841, desc = "Blackrock Spire (55, 44)" }, --Dual Wield Specialization
			{ itemID = 201056, desc = "Tirisfal Glades (70, 62)" }, --Enduring Aegis
			{ itemID = 1013656, desc = "Stranglethorn Vale (26, 13)" }, --Enrage
			{ itemID = 1013897, desc = "Silithus (25, 38)" }, --Fury Mastery
			{ itemID = 201609, desc = "Scarlet Monastery (83, 83)" }, --Gladiator Stance
			{ itemID = 201227, desc = "The Hinterlands (53, 42)" }, --Going For the Kill
			{ itemID = 201590, desc = "The Barrens (59, 27)" }, --Heavy Thunder
			{ itemID = 200611, desc = "Stranglethorn Vale (41, 83)" }, --Heavyweight
			{ itemID = 201291, desc = "The Hinterlands (54, 67)" }, --Here Comes The Big One
			{ itemID = 1300144, desc = "Un'Goro Crater (63, 62)" }, --Heroic Leap
			{ itemID = 202577, desc = "Feralas (78, 57)" }, --Heroic Rush
			{ itemID = 1013734, desc = "Stranglethorn Vale (35, 51)" }, --Impale
			{ itemID = 1013633, desc = "Blackrock Spire (39, 14)" }, --Improved Charge
			{ itemID = 1013839, desc = "Shadowfang Keep (58, 82)" }, --Improved Cleave
			{ itemID = 1013649, desc = "Loch Modan (75, 16)" }, --Improved Demoralizing Shout
			{ itemID = 1013840, desc = "Redridge Mountains (75, 37)" }, --Improved Execute
			{ itemID = 1013630, desc = "Swamp of Sorrows (45, 57)" }, --Improved Heroic Strike
			{ itemID = 1013652, desc = "Western Plaguelands (43, 15)" }, --Improved Overpower
			{ itemID = 1013629, desc = "Stratholme (70, 37)" }, --Improved Rend
			{ itemID = 1013638, desc = "Swamp of Sorrows (45, 58)" }, --Improved Revenge
			{ itemID = 1013631, desc = "Razorfen Kraul (72, 68)" }, --Improved Thunder Clap
			{ itemID = 1013936, desc = "The Temple of Atal'hakkar (24, 51)" }, --Incite
			{ itemID = 201289, desc = "Western Plaguelands (40, 72)" }, --Insatiable
			{ itemID = 1013651 }, --Iron Will
			{ itemID = 201279, desc = "Searing Gorge (49, 44)" }, --Jab Cross
			{ itemID = 201261, desc = "Arathi Highlands (54, 80)" }, --Master of Arms
			{ itemID = 201398, desc = "Burning Steppes (56, 54)" }, --Onslaught
			{ itemID = 200969, desc = "The Hinterlands (66, 71)" }, --Outrage
			{ itemID = 200631, desc = "Desolace (36, 26)" }, --Overwhelming Rage
			{ itemID = 201382, desc = "Arathi Highlands (55, 82)" }, --Power Slam
			{ itemID = 1013899, desc = "Western Plaguelands (54, 25)" }, --Protection Mastery
			{ itemID = 1013640, desc = "Stratholme (62, 77)" }, --Puncture
			{ itemID = 200122, desc = "Stranglethorn Vale (20, 12)" }, --Raging Blow
			{ itemID = 201524, desc = "Redridge Mountains (31, 15)" }, --Relentless Fury
			{ itemID = 201532, desc = "Redridge Mountains (64, 50)" }, --Revengeful Block
			{ itemID = 201324, desc = "Eastern Plaguelands (19, 27)" }, --Revitalizing Revenge
			{ itemID = 201330, desc = "Swamp of Sorrows (80, 65)" }, --Roar of Dread
			{ itemID = 201161, desc = "Azshara (52, 80)" }, --Seismic Shockwave
			{ itemID = 201014, desc = "Eastern Plaguelands (62, 34)" }, --Shield Finesse
			{ itemID = 201380, desc = "Dire Maul (75, 62)" }, --Shield Master's Resolve
			{ itemID = 1013862, desc = "Western Plaguelands (45, 44)" }, --Shield Mastery
			{ itemID = 200125, desc = "Desolace (68, 46)" }, --Siegebreaker
			{ itemID = 1013607, desc = "Dustwallow Marsh (36, 55)" }, --Spell Block
			{ itemID = 200203, desc = "Arathi Highlands (52, 52)" }, --Stormhammer
			{ itemID = 201395, desc = "Stonetalon Mountains (51, 31)" }, --Sword and Thunder
			{ itemID = 1013632, desc = "Blackrock Spire (53, 46)" }, --Tactical Mastery
			{ itemID = 1013969, desc = "Eastern Plaguelands (64, 13)" }, --Taste for Blood
			{ itemID = 201499, desc = "The Hinterlands (67, 70)" }, --Throwing Mastery
			{ itemID = 201047, desc = "Azshara (47, 77)" }, --Thundering Blow
			{ itemID = 200632, desc = "Valley of Trials (48, 3)" }, --Titan's Fury
			{ itemID = 1013634, desc = "Dustwallow Marsh (59, 10)" }, --Two-Handed Weapon Specialization
			{ itemID = 1013654, desc = "Stonetalon Mountains (30, 15)" }, --Unbridled Wrath
			{ itemID = 201530, desc = "The Barrens (52, 31)" }, --Victorious
			{ itemID = 202590 }, --Vigilant Vanguard
			{ itemID = 201400, desc = "Desolace (34, 55)" }, --War Banner
			{ icon = "INV_Box_01", name = "Glyph Scrolls" },
			{ itemID = 554170 }, --Glyph of Barbaric Insults
			{ itemID = 554280, desc = "Blackrock Spire (53, 36)" }, --Glyph of Blocking
			{ itemID = 554174, desc = "Shadowfang Keep (42, 46)" }, --Glyph of Bloodthirst
			{ itemID = 554171, desc = "Eastern Plaguelands (80, 76)" }, --Glyph of Cleaving
			{ itemID = 554184, desc = "Scholomance (52, 57)" }, --Glyph of Devastate
			{ itemID = 554172, desc = "The Hinterlands (24, 56)" }, --Glyph of Execution
			{ itemID = 554176, desc = "Lower Blackrock Mountain (37, 77)" }, --Glyph of Hamstring
			{ itemID = 554168, desc = "Jangolode Mine (62, 20)" }, --Glyph of Heroic Strike
			{ itemID = 554173, desc = "Blackrock Spire (64, 53)" }, --Glyph of Mortal Strike
			{ itemID = 554182, desc = "Western Plaguelands (48, 22)" }, --Glyph of Overpower
			{ itemID = 554166 }, --Glyph of Rapid Charge
			{ itemID = 554181, desc = "Western Plaguelands (48, 32)" }, --Glyph of Rending
			{ itemID = 554167, desc = "Loch Modan (73, 25)" }, --Glyph of Resonating Power
			{ itemID = 554169, desc = "The Hinterlands (33, 74)" }, --Glyph of Revenge
			{ itemID = 554265, desc = "Alterac Mountains (45, 30)" }, --Glyph of Shield Wall
			{ itemID = 554261 }, --Glyph of Shockwave
			{ itemID = 554264, desc = "Blackrock Spire (34, 37)" }, --Glyph of Spell Reflection
			{ itemID = 554183 }, --Glyph of Sunder Armor
			{ itemID = 554180 }, --Glyph of Sweeping Strikes
			{ itemID = 554179, desc = "Tirisfal Glades (58, 49)" }, --Glyph of Victory Rush
			{ itemID = 554175, desc = "Stranglethorn Vale (40, 8)" }, --Glyph of Whirlwind
		},
	},
})
